import { Project } from "@/types";

export const PORTFOLIO_PROJECTS: Project[] = [
  {
    title: "EcoDrive AI: Neural Route Optimization",
    slug: "logistics-oracle",
    client: "EuroTrans Group",
    industry: "Logistics & Supply Chain",
    description: "AI-driven route optimization platform that transformed manual logistics into an automated powerhouse.",
    longDescription: "EuroTrans Group faced 15% yearly losses due to manual dispatching inefficiencies. We engineered EcoDrive AI, a high-performance neural engine that processes real-time traffic, fuel consumption, and driver fatigue patterns to orchestrate a global fleet with surgical precision.",
    category: "AI & Machine Learning",
    status: "Active",
    services: ["AI Systems", "Cloud Architecture", "Deep Learning"],
    techStack: ["Next.js", "Python", "PyTorch", "PostgreSQL", "AWS SageMaker"],
    thumbnail: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=2000",
    challenge: "EuroTrans was struggling with manual dispatching and inefficient routing, leading to rising fuel costs and delivery delays.",
    solution: "We engineered a custom ERP with an AI routing engine that calculates real-time traffic, fuel efficiency, and driver availability.",
    goals: [
      "Reduce fuel consumption by 20% within 12 months",
      "Automate 90% of global dispatch workflows",
      "Implement real-time driver health monitoring"
    ],
    process: [
      { step: "Data Harvesting", description: "Auditing 10 years of legacy dispatch logs to train the foundational model." },
      { step: "Neural Training", description: "Fine-tuning PyTorch models on specific logistics edge cases." },
      { step: "Edge Deployment", description: "Provisioning AWS SageMaker endpoints for sub-second route calculation." }
    ],
    results: "40% Efficiency Gain | 22% Fuel Savings | 100% Real-time Fleet Visibility",
    metrics: [
      { label: "Efficiency Gain", value: "40%" },
      { label: "Fuel Savings", value: "22%" },
      { label: "Real-time Visibility", value: "100%" },
    ],
    detailedResults: [
      { title: "OPEX Reduction", count: "$2.4M", description: "Yearly operational savings through automated routing." },
      { title: "Time to Delivery", count: "-18%", description: "Reduction in average delivery latency across 50 countries." }
    ],
    testimonial: {
      quote: "Invinsible Tech didn't just build an app; they built the brain of our operation. Our dispatchers now handle 5x the volume with zero stress.",
      author: "Marcus Aurelius",
      role: "CTO",
      company: "EuroTrans",
    },
    screenshots: [],
    timeline: "6 Months",
    featured: true,
  },
  {
    title: "Lumina: SaaS Health Intelligence",
    slug: "lumina-saas",
    client: "Lumina Labs",
    industry: "Healthcare Technology",
    description: "High-performance B2B SaaS platform for medical data analysis and collaborative research.",
    longDescription: "Lumina Labs required a platform capable of processing genomic data while maintaining 100% HIPAA compliance. We built a high-concurrency SaaS ecosystem that allows thousands of researchers to run complex AI models on petabytes of medical data without single-point-of-failure risks.",
    category: "Websites & SaaS Platforms",
    services: ["Product Engineering", "UI/UX Design", "HIPAA Compliance"],
    techStack: ["React", "Node.js", "MongoDB", "OpenAI", "Azure Data Lake"],
    thumbnail: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=2000",
    challenge: "Researchers needed a unified platform to analyze complex medical datasets and collaborate securely in real-time.",
    solution: "We built a cloud-native SaaS platform with integrated AI analysis tools and robust HIPAA-compliant data security.",
    goals: [
      "Ensure 100% data residency and HIPAA compliance",
      "Process 1TB of genomic data in under 5 minutes",
      "Achieve SOC2 Type II certification readiness"
    ],
    process: [
      { step: "Security Audit", description: "Rigorous penetration testing and data encryption layer design." },
      { step: "SaaS Multi-tenancy", description: "Building an isolated database architecture for enterprise clients." },
      { step: "AI Integration", description: "Embedding OpenAI models for semantic search across clinical trials." }
    ],
    results: "300% User Growth | 10x Processing Speed | 99.99% Uptime",
    metrics: [
      { label: "User Growth", value: "300%" },
      { label: "Data Processing Speed", value: "10x" },
      { label: "Uptime", value: "99.99%" },
    ],
    testimonial: {
      quote: "The speed of our research has literally tripled. Invinsible Tech's engineering is as precise as our lab work.",
      author: "Sarah Chen",
      role: "Head of Research",
      company: "Lumina Labs",
    },
    screenshots: [],
    timeline: "8 Months",
    featured: true,
  },
  {
    title: "EduCore: Enterprise School ERP",
    slug: "educore-erp",
    client: "St. Mary's Academy",
    industry: "Education & EdTech",
    description: "Full-scale migration of legacy school management to a modern web-based portal.",
    longDescription: "Legacy desktop software was choking the operations of St. Mary's Academy. We executed a mission-critical digital transformation, migrating 20 years of data into a modern, multi-user ERP that handles admissions, payroll, exams, and parent communications in a single high-availability portal.",
    category: "ERP & Enterprise Software",
    status: "Featured",
    services: ["ERP Development", "Digital Transformation", "Database Design"],
    techStack: ["React", "C# .NET Core", "SQL Server", "Microsoft Azure"],
    thumbnail: "https://images.unsplash.com/photo-1523050338392-c0e7829828b0?auto=format&fit=crop&q=80&w=2000",
    challenge: "The Academy relied on outdated desktop software that caused significant administrative overhead and data silos.",
    solution: "We executed a full-scale digital transformation, building a modern school ERP that centralized all student, staff, and financial data.",
    goals: [
      "Zero data loss during legacy database migration",
      "Reduce administrative manual work by 70%",
      "Enable mobile-first access for 15,000+ parents"
    ],
    process: [
      { step: "Entity Mapping", description: "Restructuring legacy tables into a modern relational schema." },
      { step: "Portal Engineering", description: "Building accessible, high-performance dashboards for different user roles." },
      { step: "Stress Testing", description: "Simulating 5,000 concurrent logins during exam result releases." }
    ],
    results: "95% Paperless | 30h/week Admin Saved | 100% Data Integrity",
    metrics: [
      { label: "Paperless Operations", value: "95%" },
      { label: "Admin Time Saved", value: "30h/week" },
      { label: "Data Integrity", value: "100%" },
    ],
    testimonial: {
      quote: "The transformation is night and day. We used to spend weekends on paperwork; now it takes seconds.",
      author: "Fr. Thomas",
      role: "Director",
      company: "St. Mary's Academy",
    },
    screenshots: [],
    timeline: "12 Months",
    featured: true,
  },
  {
    title: "Project Phoenix: Banking Modernization",
    slug: "banking-modernization",
    client: "Global Trust Bank",
    industry: "FINTECH & BANKING",
    description: "Legacy-to-cloud migration of a core banking system handling $5B in daily transactions.",
    longDescription: "Global Trust Bank's 30-year-old mainframe was a bottleneck for mobile growth. We lead 'Project Phoenix'—a high-stakes migration that decomposed monolithic COBOL services into a resilient, Event-Driven Microservices architecture on AWS, ensuring 100% uptime during the transition.",
    category: "Modernization & Migration",
    status: "Active",
    services: ["Cloud Migration", "Microservices Architecture", "Mainframe Modernization"],
    techStack: ["Java Spring Boot", "Kafka", "PostgreSQL", "AWS EKS", "Terraform"],
    thumbnail: "https://images.unsplash.com/photo-1550565118-3a14e8d0386f?auto=format&fit=crop&q=80&w=2000",
    challenge: "A fragile mainframe architecture that prevented the bank from launching mobile-first features and scaling globally.",
    solution: "Engineering a strangler-pattern migration that replaced legacy controllers with high-performance Java microservices.",
    goals: [
      "Migrate 10M+ active accounts with zero downtime",
      "Reduce transaction processing latency by 80%",
      "Implement real-time fraud detection at the edge"
    ],
    process: [
      { step: "Mainframe Audit", description: "Mapping 4,000 legacy COBOL procedures." },
      { step: "Pilot Migration", description: "Moving non-critical services to EKS to validate the logic." },
      { step: "Full Cutover", description: "Simultaneous traffic routing across legacy and modern clusters." }
    ],
    results: "80% Latency Reduction | $10M Yearly OPEX Saved | 99.999% Reliability",
    metrics: [
      { label: "Latency Reduction", value: "80%" },
      { label: "OPEX Saved", value: "$10M/yr" },
      { label: "Reliability", value: "99.999%" },
    ],
    testimonial: {
      quote: "The team at Invinsible Tech handled our most critical assets with the precision of a surgical team.",
      author: "James Wilson",
      role: "VP Engineering",
      company: "Global Trust Bank",
    },
    screenshots: [],
    timeline: "18 Months",
    featured: false,
  },
  {
    title: "MedSync: Clinic Management OS",
    slug: "medsync-erp",
    client: "Healthcare First",
    industry: "Healthcare",
    description: "Multi-tenant ERP for specialized healthcare clinics with integrated telemedicine.",
    longDescription: "Healthcare First clinics were operating on siloed databases. We built MedSync—a global, HIPAA-compliant operating system that orchestrates patient scheduling, electronic health records (EHR), and insurance billing in a unified cloud environment.",
    category: "ERP & Enterprise Software",
    services: ["Enterprise SaaS", "EHR Development", "Cloud Infrastructure"],
    techStack: ["Next.js", "GraphQL", "Supabase", "Twilio Video", "Docker"],
    thumbnail: "https://images.unsplash.com/photo-1538108197022-863a89bc6079?auto=format&fit=crop&q=80&w=2000",
    challenge: "Data fragmentation across 12 clinics was causing double-bookings and critical billing errors.",
    solution: "A centralized, real-time dashboard with localized data residency for each clinic branch.",
    goals: [
      "Consolidate 12 fragmented databases into a single multi-tenant system",
      "Automate insurance claim processing to reduce rejection rates",
      "Implement a low-latency telemedicine portal for remote consultations"
    ],
    process: [
      { step: "Requirement Sync", description: "On-site audits at 5 major clinic branches." },
      { step: "Database Unified", description: "Executing a complex ETL process to clean and merge patient data." },
      { step: "Rollout", description: "Phase-by-phase deployment with on-site staff training." }
    ],
    results: "40% Higher Patient Throughput | 25% Billing Error Reduction | 100% HIPAA Compliance",
    metrics: [
      { label: "Patient Throughput", value: "+40%" },
      { label: "Billing Errors", value: "-25%" },
      { label: "Compliance Score", value: "100%" },
    ],
    testimonial: {
      quote: "Finally, a system that works the way doctors think. MedSync has reclaimed hours of our day from paperwork.",
      author: "Dr. Elena Rossi",
      role: "Chief Medical Officer",
      company: "Healthcare First",
    },
    screenshots: [],
    timeline: "10 Months",
    featured: false,
  },
  {
    title: "Aura: Luxury E-commerce Core",
    slug: "aura-ecommerce",
    client: "Velvet & Stone",
    industry: "Retail & E-commerce",
    description: "High-conversion headless commerce engine for a premium fashion house.",
    longDescription: "Velvet & Stone needed a digital experience that matched their physical luxury stores. We built Aura—a headless commerce platform using Shopify for the backend and a custom Next.js frontend with 3D product previews and ultra-fast page transitions.",
    category: "Websites & SaaS Platforms",
    services: ["Headless Commerce", "3D Product Design", "Performance Optimization"],
    techStack: ["Next.js", "Shopify Hydrogen", "Three.js", "Framer Motion", "Sanity"],
    thumbnail: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=2000",
    challenge: "A slow, generic Shopify template was devaluing the brand and causing a 60% bounce rate on product pages.",
    solution: "A bespoke, cinema-grade commerce engine with sub-300ms page loads and interactive 3D visualizations.",
    goals: [
      "Achieve a 100 Lighthouse performance score",
      "Increase mobile conversion rate by 50%",
      "Implement interactive 3D virtual try-ons"
    ],
    process: [
      { step: "Creative Direction", description: "Designing a high-fashion digital vernacular." },
      { step: "Headless Migration", description: "Decoupling the Shopify frontend for maximum performance." },
      { step: "3D Engineering", description: "Optimizing WebGL shaders for realistic fabric rendering." }
    ],
    results: "75% Increase in Revenue | 0.8s LCP | 35% Higher AOV",
    metrics: [
      { label: "Revenue Increase", value: "+75%" },
      { label: "Largest Contentful Paint", value: "0.8s" },
      { label: "Avg. Order Value", value: "+35%" },
    ],
    testimonial: {
      quote: "It's the first time our online presence has actually felt as premium as our brand. The results speak for themselves.",
      author: "Sofia Loren",
      role: "E-commerce Director",
      company: "Velvet & Stone",
    },
    screenshots: [],
    timeline: "5 Months",
    featured: true,
  },
  {
    title: "Stride: Performance Fitness App",
    slug: "stride-mobile",
    client: "Titan Fitness",
    industry: "Health & Fitness",
    description: "Cross-platform mobile application with real-time biometric tracking.",
    longDescription: "Stride isn't another fitness app; it's a personal data lab. We engineered a high-performance React Native app that syncs with Apple Watch and Garmin to provide real-time recovery scores using biometric data and AI coaching.",
    category: "Mobile Applications",
    status: "Active",
    services: ["Mobile Engineering", "Biometric Integration", "AI Coaching"],
    techStack: ["React Native", "Firebase", "HealthKit", "Google Fit API", "Python"],
    thumbnail: "https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&q=80&w=2000",
    challenge: "Bridging the gap between raw biometric data and actionable training advice for athletes.",
    solution: "A low-latency data pipeline that processes sensor data through custom AI recovery models.",
    goals: [
      "Achieve 4.9+ star rating on App Stores",
      "Process 1M+ heart rate data points daily per user",
      "Implement offline-first workout tracking"
    ],
    process: [
      { step: "Sensor Integration", description: "Deep diving into iOS and Android hardware APIs." },
      { step: "The Engine", description: "Building a Python-based backend for biometric analysis." },
      { step: "UI Polish", description: "Prototyping 60fps animations for real-time graphs." }
    ],
    results: "1M+ Active Downloads | 4.9 App Store Rating | 85% Retention Rate",
    metrics: [
      { label: "Active Downloads", value: "1M+" },
      { label: "App Store Rating", value: "4.9/5" },
      { label: "Retention Rate", value: "85%" },
    ],
    testimonial: {
      quote: "Stride has become the foundation of our community. The tech is invisible, but the results are everywhere.",
      author: "Coach Mike",
      role: "Lead Trainer",
      company: "Titan Fitness",
    },
    screenshots: [],
    timeline: "7 Months",
    featured: false,
  },
  {
    title: "Insight: Retail Intelligence Dashboard",
    slug: "retail-analytics",
    client: "Urban Outfitters Group",
    industry: "Retail & Big Data",
    description: "Real-time analytics platform for predictive inventory and trend forecasting.",
    longDescription: "Urban Outfitters Group needed to predict fashion trends before they hit the market. We built Insight—a massive data platform that ingests social media signals, POS data, and historical records to forecast inventory needs with 90% accuracy.",
    category: "Data & Analytics",
    services: ["Big Data Engineering", "Predictive Analytics", "Dashboard Design"],
    techStack: ["Snowflake", "dbt", "Tableau", "Python", "Apache Spark"],
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=2000",
    challenge: "Massive data silos preventing the inventory team from making data-driven stocking decisions.",
    solution: "A unified Snowflake data warehouse with real-time predictive dashboards.",
    goals: [
      "Unify 50+ disparate data sources into Snowflake",
      "Achieve 90% accuracy in stock-out forecasting",
      "Reduce excess inventory write-offs by $5M/yr"
    ],
    process: [
      { step: "Data Pipeline", description: "Engineering robust ETL flows using Spark and dbt." },
      { step: "Predictive Modeling", description: "Training time-series models on historical sales cycles." },
      { step: "Visualization", description: "Designing intuitive Tableau dashboards for non-technical buyers." }
    ],
    results: "90% Forecast Accuracy | $6M Inventory Saved | Real-time Global Triage",
    metrics: [
      { label: "Forecast Accuracy", value: "90%" },
      { label: "Capital Saved", value: "$6M/yr" },
      { label: "Dashboard Latency", value: "<2s" },
    ],
    testimonial: {
      quote: "Insight has completely removed the guesswork from our planning. We now stock with confidence.",
      author: "Rachel Green",
      role: "Director of Merchandising",
      company: "Urban Group",
    },
    screenshots: [],
    timeline: "9 Months",
    featured: true,
  },
  {
    title: "CyberPortal: Gov Modernization",
    slug: "public-service-portal",
    client: "City of New York",
    industry: "Public Sector",
    description: "Modernizing a city-wide public service portal for 8 million citizens.",
    longDescription: "The legacy public service portal was down 30% of the time. We lead the complete overhaul, building a resilient, multi-cloud portal that handles everything from tax payments to building permits with bank-grade security and zero downtime.",
    category: "Modernization & Migration",
    status: "Featured",
    services: ["Cloud Infrastructure", "API Design", "Security Engineering"],
    techStack: ["Go", "Kubernetes", "Next.js", "Redis", "Cloudflare"],
    thumbnail: "https://images.unsplash.com/photo-1517433447755-d1dd918c4424?auto=format&fit=crop&q=80&w=2000",
    challenge: "Frequent outages and high security risks in the city's critical public infrastructure.",
    solution: "A Go-based microservices architecture running on a geo-distributed Kubernetes cluster.",
    goals: [
      "Achieve 99.99% system availability",
      "Ensure compliant access for 8M citizens",
      "Implement FIPS-compliant encryption for all user data"
    ],
    process: [
      { step: "Scale Audit", description: "Analyzing 10k requests/second traffic spikes." },
      { step: "Resilient Design", description: "Building circuit breakers and high-availability clusters." },
      { step: "Security Hardening", description: "Implementing Zero Trust architecture for administrative access." }
    ],
    results: "100% Uptime | 90% Faster Access | $1.2M Hardware Saved",
    metrics: [
      { label: "Uptime", value: "100%" },
      { label: "System Speed", value: "+90%" },
      { label: "Infrastructure Cost", value: "-40%" },
    ],
    testimonial: {
      quote: "Invinsible Tech didn't just fix a website; they restored trust between the city and its citizens.",
      author: "Bill de Blasio",
      role: "Ex-Mayor",
      company: "The City of New York",
    },
    screenshots: [],
    timeline: "14 Months",
    featured: false,
  },
  {
    title: "Nova: Web3 Wallet MVP",
    slug: "crypto-wallet-mvp",
    client: "Nova Finance",
    industry: "Blockchain & DeFi",
    description: "High-security non-custodial crypto wallet for the multi-chain ecosystem.",
    longDescription: "Nova Finance needed an MVP that could compete with major players. We built a high-security, non-custodial wallet with native swap capabilities and integrated fiat-onramps in just 12 weeks.",
    category: "Startup MVPs",
    services: ["Blockchain Engineering", "MVP Development", "Security Architecture"],
    techStack: ["React Native", "ethers.js", "Solidity", "Node.js", "Web3Auth"],
    thumbnail: "https://images.unsplash.com/photo-1621416848440-236914c71ef8?auto=format&fit=crop&q=80&w=2000",
    challenge: "Complex seed-phrase management was preventing non-crypto users from entering the market.",
    solution: "Implementation of MPC (Multi-Party Computation) for social login seedless wallet recovery.",
    goals: [
      "Ship a production-ready MVP in under 90 days",
      "Support 5+ EVM-compatible chains at launch",
      "Implement one-click social recovery for wallets"
    ],
    process: [
      { step: "Seedless Logic", description: "Engineering the MPC recovery flow with Web3Auth." },
      { step: "Smart Contracts", description: "Auditing and deploying swap-aggregator contracts." },
      { step: "The Sprint", description: "12 weeks of high-velocity development and bi-weekly testing." }
    ],
    results: "100k+ Users in 1 Month | $2M TVL | Successful Seed Round",
    metrics: [
      { label: "User Acquisition", value: "100k+" },
      { label: "Total Value Locked", value: "$2M" },
      { label: "Time to Market", value: "12 Weeks" },
    ],
    testimonial: {
      quote: "They move at the speed of crypto. We went from idea to fundable MVP in exactly 3 months.",
      author: "Alex Thompson",
      role: "Founder",
      company: "Nova Finance",
    },
    screenshots: [],
    timeline: "3 Months",
    featured: false,
  },
  {
    title: "HireStream: HR Automation",
    slug: "recruitment-automation",
    client: "Apex Global",
    industry: "HR Tech",
    description: "AI-driven recruitment pipeline that automates resume screening and interview scheduling.",
    longDescription: "Apex Global's HR team was overwhelmed with 5,000+ monthly applications. We built HireStream—an automation platform that uses NLP to score resumes, conducts initial AI video screenings, and syncs calendars automatically.",
    category: "Automation & RPA",
    services: ["Intelligent Automation", "NLP Engineering", "SaaS Development"],
    techStack: ["Python", "TensorFlow", "React", "PostgreSQL", "Google Calendar API"],
    thumbnail: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&q=80&w=2000",
    challenge: "A 45-day average time-to-hire was causing Apex to lose top talent to competitors.",
    solution: "An autonomous screening layer that filters the top 5% of candidates in minutes.",
    goals: [
      "Reduce time-to-hire by 50%",
      "Automate 100% of resume screening work",
      "Eliminate interview scheduling back-and-forth"
    ],
    process: [
      { step: "NLP Training", description: "Labeling 10k resumes to train precision screening models." },
      { step: "API Engineering", description: "Integrating deeply with Gmail and Outlook calendars." },
      { step: "User Testing", description: "Iterating on candidate experience to ensure low drop-off." }
    ],
    results: "50% Faster Hiring | 90% Candidate Satisfaction | $500k/yr Saved",
    metrics: [
      { label: "Hiring Speed", value: "+50%" },
      { label: "Admin Work", value: "-90%" },
      { label: "Cost Per Hire", value: "-40%" },
    ],
    testimonial: {
      quote: "The quality of our hires has actually gone up while our workload has disappeared. Truly revolutionary.",
      author: "Kevin Hart",
      role: "Head of Talent",
      company: "Apex Global",
    },
    screenshots: [],
    timeline: "6 Months",
    featured: false,
  },
  {
    title: "LexiScan: Legal Document AI",
    slug: "legal-document-automation",
    client: "Partners & Co.",
    industry: "Legal & Professional Services",
    description: "AI platform for automated contract review and risk assessment.",
    longDescription: "Reviewing 500-page contracts used to take a team of junior lawyers three days. We built LexiScan—an AI platform that extracts key clauses, highlights risks, and generates summary reports in under 10 seconds.",
    category: "AI & Machine Learning",
    services: ["NLP Architecture", "LLM Integration", "Enterprise Software"],
    techStack: ["Python", "FastAPI", "OpenAI GPT-4", "Pinecone", "React"],
    thumbnail: "https://images.unsplash.com/photo-1589254065878-42c9da997008?auto=format&fit=crop&q=80&w=2000",
    challenge: "Human error in manual contract review was leading to significant legal risks for the firm.",
    solution: "A RAG-powered (Retrieval-Augmented Generation) document analysis system.",
    goals: [
      "Identify 10 main risk types with 98% accuracy",
      "Reduce manual review time by 95%",
      "Support automatic summarization of 50k+ precedents"
    ],
    process: [
      { step: "Embeddings", description: "Creating a vector database of legal precedents in Pinecone." },
      { step: "Logic Layer", description: "Engineering prompts and guardrails for GPT-4 analysis." },
      { step: "The Portal", description: "Designing a high-focus reading UI for legal professionals." }
    ],
    results: "98% Detection Accuracy | 10s Review Time | $1M/yr Saved",
    metrics: [
      { label: "Risk Detection", value: "98%" },
      { label: "Review Time", value: "<10s" },
      { label: "Productivity", value: "10x" },
    ],
    testimonial: {
      quote: "It's like having a senior partner verify every single clause in real-time. Unmatched precision.",
      author: "Harvey Specter",
      role: "Managing Partner",
      company: "Partners & Co.",
    },
    screenshots: [],
    timeline: "5 Months",
    featured: true,
  },
  {
    title: "FactoryMind: IoT Dashboard",
    slug: "industrial-iot",
    client: "TechMech Solutions",
    industry: "Manufacturing",
    description: "Real-time industrial IoT monitoring and predictive maintenance system.",
    longDescription: "TechMech Solutions was suffering from unexpected factory outages. We built FactoryMind—a high-concurrency IoT platform that streams data from 5,000 machines and predicts failures 48 hours in advance.",
    category: "Data & Analytics",
    services: ["IoT Engineering", "Real-time Stream Processing", "Industrial ERP"],
    techStack: ["Node.js", "InfluxDB", "MQTT", "React", "Grafana API"],
    thumbnail: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=2000",
    challenge: "Each hour of machine downtime was costing the factory over $50,000 in lost revenue.",
    solution: "A low-latency MQTT data pipeline with real-time anomaly detection models.",
    goals: [
      "Monitor 5,000+ sensors with <100ms latency",
      "Predict machine failure with 85% confidence",
      "Automate maintenance tickets via Jira integration"
    ],
    process: [
      { step: "Sensor Integration", description: "Deploying MQTT gateways across the factory floor." },
      { step: "Stream Processing", description: "Engineering the InfluxDB core for time-series data." },
      { step: "UI/UX", description: "Designing high-contrast dashboards for floor managers." }
    ],
    results: "90% Downtime Reduction | 85% Prediction Accuracy | $2M Revenue Saved",
    metrics: [
      { label: "Downtime Reduction", value: "90%" },
      { label: "Prediction Accuracy", value: "85%" },
      { label: "MTTR Reduction", value: "-50%" },
    ],
    testimonial: {
      quote: "We don't react to problems anymore; we prevent them. FactoryMind is the heartbeat of our facility.",
      author: "Elon Tusk",
      role: "Plant Manager",
      company: "TechMech",
    },
    screenshots: [],
    timeline: "11 Months",
    featured: false,
  },
  {
    title: "SwiftStock: Inventory AI",
    slug: "inventory-management",
    client: "Retail Pulse",
    industry: "Retail & Distribution",
    description: "Autonomous inventory management and supply chain forecasting.",
    longDescription: "Retail Pulse needed to eliminate stock-outs across 100+ warehouses. We built SwiftStock—an AI ERP that automatically orchestrates transfers and orders based on real-time demand signals and predictive cycles.",
    category: "ERP & Enterprise Software",
    services: ["Supply Chain Architecture", "AI Forecasting", "Enterprise ERP"],
    techStack: ["Django", "Python", "React", "Redis", "Celery"],
    thumbnail: "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&q=80&w=2000",
    challenge: "Poor distribution was causing stock-outs in 20% of locations while others were overstocked.",
    solution: "A central 'Control Tower' that handle 100% of the movement logic via AI.",
    goals: [
      "Zero stock-outs for core products",
      "Automate 100% of inter-warehouse transfers",
      "Reduce dead stock by 30% in 6 months"
    ],
    process: [
      { step: "Logistics Audit", description: "Mapping the transfer bottlenecks in the current fleet." },
      { step: "Logic Implementation", description: "Building the AI transfer engine in Django." },
      { step: "Scale Up", description: "Stress testing across 100 simultaneous warehouse nodes." }
    ],
    results: "Zero Stock-outs | 30% Dead Stock Reduction | 40% Faster Logistics",
    metrics: [
      { label: "Stock-out Rate", value: "0%" },
      { label: "Dead Stock", value: "-30%" },
      { label: "Logistics Speed", value: "+40%" },
    ],
    testimonial: {
      quote: "For the first time in years, our shelves are always full and our waste is at zero. Perfect engineering.",
      author: "Michael Scott",
      role: "Regional Manager",
      company: "Retail Pulse",
    },
    screenshots: [],
    timeline: "8 Months",
    featured: false,
  },
];
