import { ServiceDetail } from "@/types";

export const SERVICE_DETAILS: Record<string, ServiceDetail> = {
  "ai-intelligent-systems": {
    title: "AI & Intelligent Systems",
    slug: "ai-intelligent-systems",
    shortDescription: "Enterprise-grade Generative AI, Neural Engineering, RAG Systems, Cognitive Agents, and Predictive Analytics for the autonomous future.",
    description: "We don't just 'use' AI; we engineer neural systems that become the cognitive core of your business. From custom LLM fine-tuning to sophisticated RAG (Retrieval-Augmented Generation) architectures, we build software that thinks, learns, and decides at scale.",
    icon: "Brain",
    technologies: ["OpenAI", "Anthropic", "LangChain", "Pinecone", "Hugging Face", "PyTorch"],
    features: ["Generative AI & LLMs", "Custom RAG Frameworks", "Neural Search Engines", "Predictive ML Pipelines"],
    hero: {
      badge: "The Neural Vanguard",
      headline: "AI & Intelligent Systems",
      subheadline: "Cognition at Scale. Engineering the Autonomous Core.",
      intro: "In the era of rapid AI evolution, standard models are just the baseline. We engineer specialized cognitive systems—customized neural agents and private high-accuracy RAG architectures—that transform raw data into a competitive, autonomous decision-making engine for global enterprises.",
      primaryCTA: { label: "Launch AI Strategy", href: "/contact" },
      secondaryCTA: { label: "Technical Blueprint", href: "/portfolio" },
      stats: [
        { label: "Decision Velocity", value: "+300%" },
        { label: "Predictive Accuracy", value: "99.2%" },
        { label: "Opex Reduction", value: "65%" },
      ]
    },
    about: {
      description: "Our approach to AI is grounded in technical rigor and enterprise reality. We move beyond general-purpose tools to build 'Private Intelligence'—systems that are trained on your data, governed by your rules, and deployed within your secure infrastructure.",
      whyNeeded: "General AI models are generic. To win, companies need 'Specific Intelligence'—AI that understands their deep domain expertise, honors their data privacy, and integrates natively with their core legacy systems.",
      problemsSolved: [
        "Hallucination Minimization",
        "Legacy Data Cognition",
        "Decision Inconsistency",
        "Manual Triage Overload",
        "Infinite Data Fragmentation",
        "Cognitive Bottlenecks",
      ],
    },
    solutions: [
      { title: "Custom RAG Architecture", description: "Design and deployment of high-fidelity Retrieval-Augmented Generation systems using Vector DBs for zero-hallucination data querying.", icon: "Database" },
      { title: "LLM Fine-Tuning", description: "Adapting proprietary foundational models to your specific domain language and industry logic for superior performance.", icon: "Cpu" },
      { title: "Cognitive Voice Agents", description: "Ultra-low-latency, human-grade voice AI for autonomous customer service and high-volume sales triage.", icon: "Mic" },
      { title: "Predictive ML Pipelines", description: "Engineering neural networks for predictive maintenance, demand forecasting, and multi-variable risk assessment.", icon: "LineChart" },
      { title: "Neural Search Engines", description: "Semantic search systems that understand user intent and conceptual relationships rather than just keyword matches.", icon: "Search" },
      { title: "Autonomous Triage Bots", description: "AI agents that classify, prioritize, and action high-volume tickets and requests with 99.9% consistency.", icon: "Zap" },
      { title: "Computer Vision Systems", description: "Deployment of visual neural networks for automated quality control, security monitoring, and object detection.", icon: "Eye" },
      { title: "Sentiment & Intent Analysis", description: "Mass-scale linguistic analysis to detect customer sentiment and underlying intent in real-time communications.", icon: "MessageSquare" },
      { title: "Autonomous Content Engines", description: "AI-driven content generation pipelines for personalized marketing and high-velocity asset creation.", icon: "PenTool" },
      { title: "Fraud Detection Layers", description: "Real-time anomaly detection in financial transactions using pattern-recognition neural networks.", icon: "ShieldAlert" },
      { title: "AI-Driven ERP Integration", description: "Injecting intelligence into core legacy systems to automate data entry and optimize resource planning.", icon: "BarChart3" },
      { title: "Cognitive Document Capture", description: "Multimodal AI that extracts and structures data from complex, unstructured physical and digital assets.", icon: "FileText" },
      { title: "Decentralized AI Nodes", description: "Edge-AI deployment for high-performance computing without the latency or costs of central cloud servers.", icon: "Network" },
      { title: "Human-in-the-Loop Systems", description: "Workflows where AI performs high-volume work but escalates edge cases to humans for final validation.", icon: "Users" },
      { title: "AI Ethics & Governance", description: "Strategic framework implementation for bias detection, model explainability, and regulatory compliance.", icon: "Gavel" },
      { title: "Vector Database Strategy", description: "Scalable infrastructure design for high-dimensional data storage (Pinecone, Milvus, Weaviate).", icon: "Layers" },
    ],
    capabilities: [
      { title: "Cognitive Velocity", description: "Accelerating decision-making cycles from hours to milliseconds through autonomous agents.", outcome: "10x Growth Speed" },
      { title: "Precision Engineering", description: "Minimizing operational error rates through rigid, model-driven verification layers.", outcome: "99.9% Zero Error" },
      { title: "Legacy Bridging", description: "Using AI to read and action data from outdated systems that lack modern APIs.", outcome: "Full Tech Modernity" },
      { title: "Insight Harvesting", description: "Turning dark data from emails and chats into actionable business intelligence.", outcome: "360-Degree Awareness" },
      { title: "Infinite Scalability", description: "Deploying AI workloads that auto-scale based on computational demand and user volume.", outcome: "Cost-Effective Scale" },
      { title: "Neural Personalization", description: "Creating individual experiences for millions of users through real-time model inference.", outcome: "Maximized Retention" },
      { title: "Risk Mitigation", description: "Predicting financial and operational threats before they materialize through pattern recognition.", outcome: "Preserved Value" },
      { title: "Synthetic Intelligence", description: "Generating high-fidelity data sets for testing and model training in data-sparse environments.", outcome: "Faster Innovation" },
      { title: "Zero-Latency Triage", description: "Autonomous handling of 90% of incoming inquiries without human intervention.", outcome: "80% CSAT Increase" },
      { title: "Process Orchestration", description: "Using AI to coordinate multi-step workflows across different software platforms.", outcome: "Unified Operations" },
    ],
    industries: [
      { name: "FinTech", useCase: "Real-time fraud prevention & algorithmic credit scoring." },
      { name: "Healthcare", useCase: "AI-assisted diagnostics & patient data orchestration." },
      { name: "Manufacturing", useCase: "Predictive maintenance & automated visual QC." },
      { name: "E-commerce", useCase: "Hyper-personalized search & sentiment-driven support." },
      { name: "Logistics", useCase: "Autonomous routing optimization & supply chain forecasting." },
      { name: "Real Estate", useCase: "Automated valuation models & document triage." },
      { name: "Real Estate", useCase: "Automated valuation models & document triage." },
      { name: "LegalTech", useCase: "Contract analysis & semantic case research." },
      { name: "Education", useCase: "Customized learning paths & automated grading bots." },
    ],
    process: [
      { title: "AI Strategy Deep-Dive", description: "Identifying high-ROI AI opportunities and data readiness assessments." },
      { title: "Architecture Design", description: "Blueprint for RAG, Vector DBs, and model selection (OpenAI, Claude, Llama 3)." },
      { title: "Data Preparation", description: "Cleaning, chunking, and embedding your proprietary data for model consumption." },
      { title: "Model Engineering", description: "Fine-tuning models and building custom prompt-engineering layers." },
      { title: "Deployment & Scaling", description: "Launching into production with real-time monitoring and security layers." },
      { title: "Recursive Learning", description: "Implementing feedback loops to continuously improve model accuracy." },
    ],
    benefits: [
      { title: "Cognitive Dominance", description: "Out-think competitors by leveraging hidden data patterns in real-time.", icon: "Zap" },
      { title: "Radical Efficiency", description: "Reclaim thousands of man-hours from repetitive intellectual triage.", icon: "Activity" },
      { title: "Unbeatable Accuracy", description: "Eliminate human fatigue errors in high-stakes data processing.", icon: "Target" },
      { title: "Future-Proof Edge", description: "Build on the architecture of tomorrow, today.", icon: "TrendingUp" },
    ],
    faq: [
      { question: "How do you handle data privacy with AI?", answer: "We implement 'Private AI' instances and can run models entirely within your VPC, ensuring your proprietary data never leaves your secure environment or trains public models." },
      { question: "What is RAG and why do we need it?", answer: "Retrieval-Augmented Generation allows AI to query your private documents for high-accuracy, zero-hallucination answers. It turns a general model into a specialist for your business." },
      { question: "Can we use AI with our legacy database?", answer: "Yes, we build secure ETL pipelines and semantic index layers that make legacy data accessible to modern neural agents." },
      { question: "What is the typical timeline for an AI pilot?", answer: "We typically launch a functional Proof-of-Concept (POC) in 4 to 6 weeks, with full production scaling in 3 to 4 months." },
      { question: "How much does it cost to train a custom model?", answer: "Through techniques like LoRA (Low-Rank Adaptation), we can fine-tune enterprise models for a fraction of the cost of full training." },
      { question: "Will the AI hallucinate info?", answer: "We use 'Fact-Anchoring' and rigid RAG architectures which force the AI to only cite provided documentation, virtually eliminating false information." },
      { question: "Do we need an internal ML team?", answer: "No, we provide 'AI-as-a-Service' (AIaaS) where we monitor, update, and optimize your models as part of our ongoing partnership." },
      { question: "Can AI handle complex multi-step tasks?", answer: "Yes, we build 'Autonomous Agents' that can plan, execute, and verify multi-step workflows across your tech stack." },
      { question: "Which LLM is best: OpenAI or Anthropic?", answer: "Each has strengths. We choose based on your needs—OpenAI for pure power, Anthropic for safety/context, or Llama 3 for local privacy." },
      { question: "Is my data used to train OpenAI's models?", answer: "Not when using Enterprise API tiers. We ensure strict contractual and technical boundaries where your data is never reused." },
      { question: "What is a Vector Database?", answer: "It's a specialized database (like Pinecone) that stores data as 'embeddings' allowing AI to perform conceptual, high-speed semantic searches." },
      { question: "How do you measure AI ROI?", answer: "We track 'Regained Intellectual Hours,' 'Error Rate Reduction,' and 'Decision Latency.' Most projects show full ROI within 12 months." },
      { question: "Can AI triage my company's support emails?", answer: "Yes, we've built agents that handle 80% of email triage with high empathy and 100% policy compliance." },
      { question: "What happens if AI makes a mistake?", answer: "We implement 'High-Impact Guards.' AI handles the volume, but 'Human-in-the-Loop' protocols route critical decisions to your experts." },
      { question: "How do we get started with an AI strategy?", answer: "Start with an AI Readiness Audit. We'll map your data and identify the single most impactful workflow to automate first." },
    ],
    techStack: [
      { category: "LLMs & GenAI", items: ["GPT-4o", "Claude 3.5 Sonnet", "Llama 3 (8B/70B)", "Mistral Large"] },
      { category: "Neural Frameworks", items: ["PyTorch", "TensorFlow", "JAX", "Hugging Face Transformers"] },
      { category: "Vector & RAG Ops", items: ["Pinecone", "Milvus", "Weaviate", "LangChain", "LlamaIndex"] },
      { category: "Cloud AI & MLOps", items: ["AWS SageMaker", "Google Vertex AI", "Azure Machine Learning", "Docker"] },
    ],
    toolLogos: [
      { name: "OpenAI", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg" },
      { name: "Anthropic", logo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Anthropic_logo.svg?v=1" },
      { name: "Hugging Face", logo: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Hugging_Face_logo.svg" },
      { name: "LangChain", logo: "https://raw.githubusercontent.com/langchain-ai/langchain/master/docs-v2/static/img/brand/wordmark.png" },
      { name: "Pinecone", logo: "https://assets.website-files.com/62cdee5a73e3467f502ac127/62cede65985b9b7754f24300_Pinecone%20Logo.svg" },
      { name: "NVIDIA", logo: "https://upload.wikimedia.org/wikipedia/commons/2/21/Nvidia_logo.svg" },
      { name: "PyTorch", logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo.icon.svg" },
      { name: "TensorFlow", logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" },
      { name: "Llama Index", logo: "https://raw.githubusercontent.com/run-llama/llama_index/main/docs/_static/logo.png" },
      { name: "Milvus", logo: "https://raw.githubusercontent.com/milvus-io/milvus/master/assets/logo.png" },
      { name: "AWS SageMaker", logo: "https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-immersion-day/master/img/amazon-sagemaker.png" },
      { name: "Google Vertex AI", logo: "https://upload.wikimedia.org/wikipedia/commons/2/23/Google_Cloud_Logo.svg" },
      { name: "Databricks", logo: "https://upload.wikimedia.org/wikipedia/commons/6/63/Databricks_Logo.svg" },
    ],
    finalCTA: {
      headline: "Stop waiting on the future. Engineer it.",
      description: "Let's architect an AI solution that puts your enterprise ten steps ahead of the competition.",
      buttonLabel: "Book an AI Consultation",
    },
  },
  "digital-transformation": {
    title: "Digital Transformation",
    slug: "digital-transformation",
    shortDescription: "End-to-end modernization, process optimization, technology consulting, and digital architecture for future-ready organizations.",
    description: "We help institutions and enterprises migrate from legacy systems to high-performance, cloud-native technology stacks. Our approach covers strategic consulting, architecture planning, and seamless zero-downtime execution.",
    icon: "RefreshCw",
    technologies: ["Next.js", "Python", "AWS", "Docker"],
    features: ["Legacy Modernization", "Cloud Migration", "Strategy & Consulting", "Infrastructure Audit"],
    hero: {
      badge: "Modernization",
      headline: "Digital Transformation",
      subheadline: "Modernize the core. Orchestrate the future.",
      intro: "Stop fighting outdated tech. We re-engineer legacy architectures into high-performance, cloud-native ecosystems that turn operational friction into market-leading speed.",
      primaryCTA: { label: "Consult an Architect", href: "/contact" },
      secondaryCTA: { label: "Explore Strategy", href: "#solutions" },
      stats: [
        { label: "Legacy Code Refactored", value: "2M+ Lines" },
        { label: "Cloud Uptime", value: "99.99%" },
        { label: "Cost Reduction", value: "30%" },
      ],
    },
    about: {
      description: "Digital transformation is not about buying new tools; it's about re-engineering your operational DNA. We help enterprises shed the weight of legacy systems and transition to modern, API-first architectures.",
      whyNeeded: "Legacy systems are the silent killer of enterprise agility. To compete today, your infrastructure must be as fluid and scalable as the market itself.",
      problemsSolved: [
        "Eliminates technical debt and maintenance spikes",
        "Breaks down fragmented data silos",
        "Automates zero-downtime cloud migrations",
        "Modernizes mission-critical legacy codebases",
      ],
    },
    solutions: [
      { title: "Legacy Modernization", description: "Refactoring monoliths into modular microservices without disrupting live operations.", icon: "RefreshCw" },
      { title: "Cloud Migration", description: "Strategic lifting and shifting to AWS, Azure, or GCP with a focus on cost-optimization.", icon: "Cloud" },
      { title: "API-First Architecture", description: "Orchestrating high-performance internal and external API networks for seamless data flow.", icon: "Code2" },
      { title: "Infrastructure Audit", description: "Deep-dive technical assessment of security, performance, and scalability bottlenecks.", icon: "Shield" },
      { title: "Process Optimization", description: "Mapping and automating manual business workflows through custom digital tools.", icon: "Zap" },
    ],
    capabilities: [
      { title: "Zero-Downtime Migration", description: "Transitioning high-traffic platforms to new stacks without a single second of service loss.", useCase: "Fintech Platform Upgrades", outcome: "100% Availability" },
      { title: "Microservices Architecture", description: "Building resilient, decoupled systems that allow independent scaling of features.", useCase: "Enterprise ERP Overhauls", outcome: "4x Faster Deployments" },
      { title: "Security Modernization", description: "Implementing Zero-Trust architectures and advanced encryption across all legacy endpoints.", useCase: "HIPAA Compliance", outcome: "SOC2 Ready" },
    ],
    industries: ["Finance", "Healthcare", "Logistics", "Manufacturing", "Government"],
    process: [
      { title: "Audit", description: "Full technical audit of existing legacy infrastructure." },
      { title: "Strategy", description: "Architectural blueprint and migration roadmap." },
      { title: "Modernization", description: "Sprinting to refactor or rebuild core components." },
      { title: "Migration", description: "Phased cloud-native deployment with zero downtime." },
      { title: "Training", description: "Enabling your internal team to manage the new stack." },
      { title: "Scaling", description: "Continuous performance tuning and infrastructure management." },
    ],
    techStack: [
      { category: "Cloud-Native", items: ["AWS", "Azure", "GCP", "Kubernetes", "Docker", "Terraform"] },
      { category: "Backend", items: ["Python", "Node.js", "Go", "Java Spring", "Rust", "FastAPI"] },
      { category: "Automation", items: ["GitHub Actions", "Ansible", "Jenkins", "CircleCI"] },
      { category: "Database", items: ["PostgreSQL", "MongoDB", "Redis", "Elasticsearch", "SQL Server"] },
    ],
    toolLogos: [
      { name: "AWS", logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg" },
      { name: "Azure", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Microsoft_Azure_Logo.svg" },
      { name: "GCP", logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/Google_Cloud_logo.svg" },
      { name: "Docker", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Docker_%28container_engine%29_logo.svg" },
      { name: "Kubernetes", logo: "https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_v2.svg" },
      { name: "Terraform", logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/Terraform_Logo.svg" },
      { name: "GitHub", logo: "https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg" },
      { name: "Jenkins", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Jenkins_logo.svg" },
      { name: "Ansible", logo: "https://upload.wikimedia.org/wikipedia/commons/2/24/Ansible_logo.svg" },
    ],
    benefits: [
      { title: "Radical Agility", description: "Ship features 10x faster with a modern dev ecosystem.", icon: "Zap" },
      { title: "Cost Efficiency", description: "Reduce server and maintenance overhead by ups to 40%.", icon: "TrendingDown" },
      { title: "Absolute Security", description: "Move from legacy vulnerabilities to modern encryption standards.", icon: "ShieldCheck" },
      { title: "Linear Scalability", description: "Infrastructure that grows automatically with your user base.", icon: "ArrowUpRight" },
    ],
    faq: [
      { question: "Will our service be offline during the migration?", answer: "No. We specialize in zero-downtime migrations using blue-green deployment strategies to ensure 100% availability." },
      { question: "How long does a typical digital transformation take?", answer: "Phased modernization usually delivers the first visible wins in 8-12 weeks, with full enterprise shifts occurring over 6-12 months." },
      { question: "Do you work with existing in-house dev teams?", answer: "Yes, we often act as an 'Elite Strike Team' that works alongside your internal developers to architect and implement the core shift." },
    ],
    caseStudy: {
      projectSlug: "supply-chain-modernization",
      overview: "Transformed a 20-year-old monolithic logistics system into a cloud-native API powerhouse, increasing fulfillment speed by 250%.",
    },
    finalCTA: {
      headline: "Modernize or be left behind.",
      description: "Let's architect a digital transformation roadmap that turns your infrastructure into a competitive weapon.",
      buttonLabel: "Start Your Modernization",
    },
  },
  "product-enterprise-engineering": {
    title: "Product & Enterprise Engineering",
    slug: "product-enterprise-engineering",
    shortDescription: "Custom SaaS platforms, ERP, CRM, HRMS, and scalable business applications designed for complex global operations.",
    description: "From idea to market-ready SaaS or enterprise-wide internal systems, we engineer scalable, high-performance software using modern architecture and robust security.",
    icon: "Code2",
    technologies: ["React", "Node.js", "TypeScript", "PostgreSQL", "Java", "C#"],
    features: ["SaaS & MVP Dev", "Custom ERP & CRM", "HRMS & Internal Portals", "Scalable App Architecture"],
    hero: {
      badge: "Engineering Excellence",
      headline: "Product & Enterprise Engineering",
      subheadline: "Built for high scale. Engineered for absolute reliability.",
      intro: "From disruptive SaaS platforms to heavy-duty internal ERPs, we build the robust software foundations that power global businesses and billion-dollar operations.",
      primaryCTA: { label: "Build Your Platform", href: "/contact" },
      secondaryCTA: { label: "View Systems", href: "#solutions" },
      stats: [
        { label: "Production Up", value: "99.9%" },
        { label: "Users Managed", value: "1M+" },
        { label: "Security", value: "Enterprise" },
      ],
    },
    about: {
      description: "We don't just build apps; we engineer complex ecosystems. Whether it's a multi-tenant SaaS or a mission-critical internal CRM, we focus on technical longevity and performance.",
      whyNeeded: "Off-the-shelf software creates operational friction. Custom platforms allow you to map software perfectly to your unique competitive business logic.",
      problemsSolved: [
        "Fragmented internal data across siloed spreadsheets",
        "Slow, unscalable tools that break under moderate load",
        "Manual ERP tasks costing thousands in man-hours",
        "Lack of product-market readiness for startups",
      ],
    },
    solutions: [
      { title: "SaaS & MVP Development", description: "Rapid engineering of scalable multi-tenant platforms designed for growth and fundraising.", icon: "Zap" },
      { title: "Custom ERP Systems", description: "Centralizing finance, logistics, and management into a single, high-performance dashboard.", icon: "Layout" },
      { title: "CRM & Internal Portals", description: "Bespoke internal tools for customer management and automated sales workflows.", icon: "Users" },
      { title: "Educational Management", description: "Comprehensive school and university portals for students, staff, and admin.", icon: "GraduationCap" },
      { title: "API Development", description: "Building the robust backend engines that connect your entire business ecosystem.", icon: "Globe" },
    ],
    capabilities: [
      { title: "Multi-Tenant Architecture", description: "Scalable SaaS foundations that support thousands of secure, isolated client databases.", useCase: "B2B SaaS Growth", outcome: "Infinitely Scalable" },
      { title: "Real-Time Dashboards", description: "High-performance data visualization for instant business intelligence and reporting.", useCase: "Executive Decision Making", outcome: "Zero-Latency Insights" },
      { title: "Secure Authentication", description: "Enterprise-grade SSO, OAuth, and multi-layered security protocols for internal data protection.", useCase: "HRMS & Payroll Portals", outcome: "Absolute Data Security" },
    ],
    industries: ["Education", "Logistics", "Retail", "Manufacturing", "Tech Startups"],
    process: [
      { title: "Consultancy", description: "Deep mapping of business logic and system requirements." },
      { title: "Architecting", description: "Database design and choosing the right engineering stack." },
      { title: "Development", description: "Agile sprints with bi-weekly production-ready releases." },
      { title: "Quality Control", description: "Rigorous stress-testing and automated unit/e2e testing." },
      { title: "Scaling", description: "Optimizing code and queries for massive user concurrent load." },
      { title: "Evolution", description: "Continuous feature engineering and version upgrades." },
    ],
    techStack: [
      { category: "Frontend", items: ["Next.js", "TypeScript", "React", "Tailwind CSS", "Vue.js", "Angular", "Svelte"] },
      { category: "Backend", items: ["Node.js", "Express", "Python", "Django", "FastAPI", "Java Spring", "Ruby on Rails"] },
      { category: "Databases", items: ["PostgreSQL", "MongoDB", "Redis", "Elasticsearch", "MySQL", "Cassandra"] },
      { category: "Enterprise", items: ["C#", ".NET Core", "Java", "SQL Server", "Oracle", "SAP"] },
    ],
    toolLogos: [
      { name: "React", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" },
      { name: "Next.js", logo: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Nextjs-logo.svg" },
      { name: "Django", logo: "https://upload.wikimedia.org/wikipedia/commons/7/75/Django_logo.svg" },
      { name: "Node.js", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg" },
      { name: "Python", logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" },
      { name: "PostgreSQL", logo: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg" },
      { name: "MongoDB", logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/MongoDB_Logo.svg" },
      { name: "Spring", logo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Spring_Framework_Logo_2018.svg" },
      { name: "DotNet", logo: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Microsoft_.NET_logo.svg" },
      { name: "Java", logo: "https://upload.wikimedia.org/wikipedia/en/3/30/Java_programming_language_logo.svg" },
      { name: "TypeScript", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg" },
    ],
    benefits: [
      { title: "Product Longevity", description: "Systems built to last and evolve with your business.", icon: "ShieldCheck" },
      { title: "Market Readiness", description: "High-performance code that is ready for millions of users.", icon: "Rocket" },
      { title: "Operational Flow", description: "Eliminate manual friction with automated internal tools.", icon: "Activity" },
      { title: "Data Integrity", description: "Single source of truth across your entire organization.", icon: "Database" },
    ],
    faq: [
      { question: "Can you build a full MVP in 8 weeks?", answer: "Yes. Our 'SaaS Strike' protocol is designed to deliver a high-quality, scalable MVP ready for launch in roughly 2 months." },
      { question: "Do you provide post-launch maintenance?", answer: "Absolutely. We offer tailored SLA packages for continuous feature development, security monitoring, and scaling." },
      { question: "Can your custom ERP integrate with our current tools?", answer: "Yes, we specialize in building custom API bridges to sync with tools like Salesforce, SAP, and Quickbooks." },
    ],
    caseStudy: {
      projectSlug: "school-management-erp",
      overview: "Engineered a custom ERP that synchronized data across 50+ campuses, reducing administrative manual work by 75%.",
    },
    finalCTA: {
      headline: "Engineered for success.",
      description: "Let's build the robust software foundation your business deserves.",
      buttonLabel: "Get a Platform Audit",
    },
  },
  "website-design": {
    title: "Website & Experience Design",
    slug: "website-design",
    shortDescription: "Premium websites, 3D experiences, landing pages, e-commerce platforms, and high-performance digital interfaces.",
    description: "We craft visually stunning, high-performance websites and digital experiences that blend aesthetic excellence with technical precision.",
    icon: "Monitor",
    technologies: ["Next.js", "Three.js", "Tailwind CSS", "Framer Motion"],
    features: ["Premium Marketing Sites", "3D Web Experiences", "E-commerce Platforms", "UI/UX Design"],
    hero: {
      badge: "Digital Experience",
      headline: "Website & Experience Design",
      subheadline: "Visual excellence. Technical precision.",
      intro: "We don't just build websites; we engineer immersive digital environments. From hyper-fast headless storefronts to interactive 3D experiences, we blend aesthetic mastery with bleeding-edge performance.",
      primaryCTA: { label: "Design Your Experience", href: "/contact" },
      secondaryCTA: { label: "View Portfolio", href: "/portfolio" },
      stats: [
        { label: "Lighthouse Score", value: "100/100" },
        { label: "Conversion Lift", value: "+45%" },
        { label: "3D Interactions", value: "Smooth" },
      ],
    },
    about: {
      description: "In a world of generic templates, we provide custom-engineered digital identities. We focus on the intersection of brand storytelling and technical performance to create websites that convert.",
      whyNeeded: "Your website is your 24/7 global headquarters. A slow, generic site isn't just a missed opportunity—it's a liability to your brand's perceived authority.",
      problemsSolved: [
        "Eliminates slow load times and poor SEO rankings",
        "Replaces generic templates with unique brand identities",
        "Simplifies complex e-commerce workflows",
        "Adds interactive 3D elements for maximum engagement",
      ],
    },
    solutions: [
      { title: "Bespoke Marketing Sites", description: "High-performance corporate websites built with Next.js and optimized for search and conversion.", icon: "Layout" },
      { title: "3D Web Experiences", description: "Immersive WebGL and Three.js environments that bring your products to life in the browser.", icon: "Box" },
      { title: "Headless E-commerce", description: "Custom-built shopping experiences using Shopify Hydrogen or BigCommerce APIs for ultimate speed.", icon: "ShoppingBag" },
      { title: "High-Conversion Landers", description: "Data-driven landing pages designed specifically for performance marketing and paid campaigns.", icon: "Target" },
      { title: "Interactive Prototypes", description: "High-fidelity digital proof-of-concepts to test ideas before full-scale engineering.", icon: "Figma" },
    ],
    capabilities: [
      { title: "Performance Engineering", description: "Optimizing Core Web Vitals to ensure sub-second load times and perfect SEO scores.", useCase: "Global Marketing Sites", outcome: "100 Lighthouse Score" },
      { title: "Motion & Interaction", description: "Advanced Framer Motion and GSAP animations that guide the user journey without friction.", useCase: "Premium SaaS Websites", outcome: "Higher Engagement" },
      { title: "CMS Orchestration", description: "Integratingheadless CMS solutions like Sanity or Contentful for effortless internal content management.", useCase: "Enterprise Portals", outcome: "Zero-Code Editing" },
    ],
    industries: ["SaaS", "Luxury Brands", "Real Estate", "D2C Retail", "Agencies"],
    process: [
      { title: "Creative Strategy", description: "Mapping brand voice and user conversion journeys." },
      { title: "UX/UI Prototyping", description: "High-fidelity design sprints in Figma with real interactions." },
      { title: "Frontend Engineering", description: "Pixel-perfect Next.js development with custom CSS." },
      { title: "Motion Design", description: "Integrating animations and 3D elements for a premium feel." },
      { title: "SEO Optimization", description: "Technical SEO and speed tuning for global reach." },
      { title: "Launch & Support", description: "Deployment and continuous conversion rate optimization." },
    ],
    techStack: [
      { category: "Frontend", items: ["Next.js", "React", "TypeScript", "Tailwind CSS", "SvelteKit", "Hono"] },
      { category: "Animation", items: ["Framer Motion", "GSAP", "Three.js", "WebGL", "Rive", "Spline"] },
      { category: "Headless CMS", items: ["Sanity", "Contentful", "Strapi", "Storyblok", "Shopify Hydrogen"] },
      { category: "Design & Dev", items: ["Figma", "Adobe CC", "Vercel", "Netlify", "Cloudflare"] },
    ],
    toolLogos: [
      { name: "Next.js", logo: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Nextjs-logo.svg" },
      { name: "React", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" },
      { name: "Tailwind", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg" },
      { name: "Figma", logo: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg" },
      { name: "Sanity", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Sanity_Logo.svg" },
      { name: "Three.js", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Three.js_Icon.svg" },
      { name: "Shopify", logo: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Shopify_logo_2018.svg" },
      { name: "Vercel", logo: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Vercel_logo_black.svg" },
      { name: "Svelte", logo: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Svelte_Logo.svg" },
    ],
    benefits: [
      { title: "Stunning ROI", description: "High-conversion designs that turn visitors into loyal clients.", icon: "TrendingUp" },
      { title: "Elite Load Speeds", description: "Sub-second performance that keeps users on your page.", icon: "Zap" },
      { title: "Brand Authority", description: "Custom visual language that positions you as a market leader.", icon: "Award" },
      { title: "Search Dominance", description: "Perfect technical SEO foundations for organic growth.", icon: "Search" },
    ],
    faq: [
      { question: "Do you use WordPress or generic templates?", answer: "Never. We build custom-coded, high-performance websites using modern stacks like Next.js to ensure maximum speed and unique branding." },
      { question: "How involved are we in the design process?", answer: "Extremely. We run collaborative Figma sprints where you see every iteration and provide feedback before a single line of code is written." },
      { question: "Can we manage the content ourselves?", answer: "Yes. Every site we build is connected to a headless CMS (like Sanity) that allows your marketing team to edit text and images without a developer." },
    ],
    caseStudy: {
      projectSlug: "luxury-real-estate-portal",
      overview: "Designed an interactive 3D property explorer that increased lead generation by 180% through immersive storytelling.",
    },
    finalCTA: {
      headline: "Stop blending in. Start leading.",
      description: "Let's engineer a digital experience that captures your brand's absolute potential.",
      buttonLabel: "Design Your Future",
    },
  },
  "mobile-engineering": {
    title: "Mobile App Engineering",
    slug: "mobile-engineering",
    shortDescription: "Cross-platform Android and iOS applications for startups, enterprises, internal teams, and customer-facing products.",
    description: "We develop high-performance, cross-platform mobile applications that prioritize user experience and technical efficiency.",
    icon: "Smartphone",
    technologies: ["React Native", "Flutter", "Swift", "Kotlin"],
    features: ["iOS & Android Apps", "React Native", "UI/UX Motion", "Mobile Backend Integration"],
    hero: {
      badge: "Mobile Architecture",
      headline: "Mobile App Engineering",
      subheadline: "Uncompromising performance. Native feel.",
      intro: "We engineer high-performance, cross-platform mobile applications that bridge the gap between technical complexity and intuitive user design. From enterprise tools to viral consumer apps, we build for the pocket.",
      primaryCTA: { label: "Build Your App", href: "/contact" },
      secondaryCTA: { label: "Explore Features", href: "#solutions" },
      stats: [
        { label: "Platform Coverage", value: "iOS + Android" },
        { label: "App Store Rating", value: "4.9/5" },
        { label: "Reliability", value: "99.9%" },
      ],
    },
    about: {
      description: "Developing for mobile requires a focus on battery life, gesture-driven UX, and offline reliability. We specialize in React Native and Flutter to deliver near-native performance with single-codebase efficiency.",
      whyNeeded: "A mobile app isn't just a mobile website—it's a direct connection to your user's daily life. To be successful, it must be fast, offline-capable, and gesture-perfect.",
      problemsSolved: [
        "Slow, clunky hybrid apps that feel like websites",
        "High maintenance costs of separate iOS/Android teams",
        "Poor offline functionality in critical business tools",
        "Complex backend integrations with mobile endpoints",
      ],
    },
    solutions: [
      { title: "React Native Apps", description: "Developing high-performance iOS and Android apps with a single, maintainable TypeScript codebase.", icon: "Smartphone" },
      { title: "Flutter Development", description: "Bespoke mobile experiences with rich custom UI and pixel-perfect rendering across all devices.", icon: "Cpu" },
      { title: "Enterprise Field Tools", description: "Offline-first mobile applications for logistics, quality control, and field operations.", icon: "Shield" },
      { title: "Consumer SaaS Apps", description: "Feature-rich mobile extensions for your existing web platforms with push notification engines.", icon: "Zap" },
      { title: "Mobile UI/UX Design", description: "Gesture-driven, motion-heavy mobile design that prioritizes Thumb-Zone ergonomics.", icon: "Palette" },
    ],
    capabilities: [
      { title: "Offline-First Sync", description: "Seamless local-first data caching and background synchronization for low-connectivity environments.", useCase: "Field Logistics Apps", outcome: "100% Data Uptime" },
      { title: "Native Module Bridging", description: "Accessing device-specific features like Biometrics, GPS, Camera, and Bluetooth at native speeds.", useCase: "Secure Fintech Apps", outcome: "Native Performance" },
      { title: "Push Orchestration", description: "Advanced user segmentation and automated push notification workflows for higher retention.", useCase: "E-commerce Apps", outcome: "2x User Retention" },
    ],
    industries: ["Fintech", "Logistics", "Healthcare", "On-Demand Services", "EdTech"],
    process: [
      { title: "Mobile Strategy", description: "Mapping user personas and gesture-based user flows." },
      { title: "High-Fidelity UI", description: "Designing the app in Figma with a focus on Thumb-Zone accessibility." },
      { title: "App Engineering", description: "Cross-platform development with continuous beta testing." },
      { title: "API Integration", description: "Connecting the mobile frontend to secure, high-speed backend engines." },
      { title: "Quality Assurance", description: "Testing on 50+ device/OS combinations for absolute stability." },
      { title: "Store Deployment", description: "Managing the entire App Store and Play Store submission process." },
    ],
    techStack: [
      { category: "Frameworks", items: ["React Native", "Flutter", "Expo", "SwiftUI", "Jetpack Compose", "Ionic"] },
      { category: "State & Data", items: ["Zustand", "Redux Toolkit", "React Query", "GraphQL", "Apollo"] },
      { category: "Mobile Backend", items: ["Firebase", "Supabase", "Appwrite", "Node.js", "PostgreSQL"] },
      { category: "Ops & Ship", items: ["Fastlane", "GitHub Actions", "TestFlight", "Codepush"] },
    ],
    toolLogos: [
      { name: "Apple", logo: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg" },
      { name: "Android", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Android_robot.svg" },
      { name: "Flutter", logo: "https://upload.wikimedia.org/wikipedia/commons/1/17/Google-flutter-logo.png" },
      { name: "React", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" },
      { name: "Expo", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Expo_logo.svg" },
      { name: "Firebase", logo: "https://upload.wikimedia.org/wikipedia/commons/3/37/Firebase_Logo.svg" },
      { name: "Supabase", logo: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Supabase_logo.svg" },
      { name: "GraphQL", logo: "https://upload.wikimedia.org/wikipedia/commons/1/17/GraphQL_Logo.svg" },
      { name: "Swift", logo: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Swift_logo.svg" },
      { name: "Kotlin", logo: "https://upload.wikimedia.org/wikipedia/commons/7/74/Kotlin_Icon.svg" },
    ],
    benefits: [
      { title: "Universal Reach", description: "One codebase for both iOS and Android platforms.", icon: "Globe" },
      { title: "Zero Latency", description: "Native-level performance for smooth scrolling and complex interactions.", icon: "Zap" },
      { title: "Deep Engagement", description: "Leverage push notifications to keep your brand in front of users.", icon: "Bell" },
      { title: "Security First", description: "Biometric auth and encrypted local storage for sensitive data.", icon: "Lock" },
    ],
    faq: [
      { question: "Should we choose React Native or Flutter?", answer: "It depends on your project goals. React Native is great for web-aligned teams, while Flutter excels in highly custom visuals. We'll help you decide during discovery." },
      { question: "How do you handle App Store rejections?", answer: "We don't just build; we consult. We ensure your app follows all Apple and Google guidelines before submission to ensure a 100% approval rate." },
      { question: "Can the app work without an internet connection?", answer: "Yes, we build offline-first applications that store data locally and sync with the server once connectivity is restored." },
    ],
    caseStudy: {
      projectSlug: "fintech-mobile-wallet",
      overview: "Built a secure, biometrically-enabled mobile wallet that processed over $10M in transactions within the first 6 months.",
    },
    finalCTA: {
      headline: "The future is in their pockets.",
      description: "Let's engineer a mobile experience that your users will actually love to use every day.",
      buttonLabel: "Start Your Mobile Build",
    },
  },
  "intelligent-automation": {
    title: "Intelligent Automation (RPA+AI)",
    slug: "intelligent-automation",
    shortDescription: "Enterprise-grade RPA, intelligent workflows, CRM automation, document processing, and AI-powered operations for global scale.",
    description: "We eliminate operational friction by replacing repetitive manual tasks with high-reliability autonomous agents and intelligent software workflows.",
    icon: "Zap",
    technologies: ["UiPath", "Power Automate", "Python", "Zapier", "OpenAI"],
    features: ["Robotic Process Automation", "Intelligent Workflows", "AI Document Processing", "CRM & ERP Automation"],
    hero: {
      badge: "Automation & RPA Architecture",
      headline: "Intelligent Automation (RPA+AI)",
      subheadline: "Eliminate Friction. Engineering Enterprise Flow.",
      intro: "We replace repetitive manual labor with high-reliability autonomous agents. From complex RPA bots to AI-driven document processing, we engineer the digital nervous system that allows your enterprise to focus on high-level strategic growth.",
      primaryCTA: { label: "Automate Your Enterprise", href: "/contact" },
      secondaryCTA: { label: "View RPA Solutions", href: "#solutions" },
      stats: [
        { label: "Man-Hours Saved", value: "100k+" },
        { label: "Process Accuracy", value: "100%" },
        { label: "Manual Work Reduction", value: "90%" },
        { label: "Faster Turnaround", value: "75%" },
      ],
    },
    about: {
      description: "Intelligent automation is the fusion of Robotic Process Automation (RPA) and Artificial Intelligence. We don't just build scripts; we architect systems that learn, adapt, and handle complex exceptions across your entire enterprise stack.",
      whyNeeded: "Manual data entry and repetitive admin tasks are the 'silent friction' that kills enterprise agility. Automation isn't just a cost-saving measure—it's about gaining absolute precision and market-leading speed.",
      problemsSolved: [
        "Eliminates costly human errors in high-stakes data entry",
        "Reduces invoice and document processing time from days to seconds",
        "Synchronizes data across legacy apps without native API support",
        "Automates complex, multi-step back-office financial workflows",
      ],
    },
    solutions: [
      { title: "Robotic Process Automation", description: "Deploying high-reliability software bots to execute repetitive UI-based tasks across any desktop or web application.", icon: "Bot" },
      { title: "CRM Automation", description: "Automating lead routing, follow-ups, and data enrichment to hyper-accelerate your sales cycle.", icon: "Users" },
      { title: "Email Automation", description: "Intelligent sorting, response generation, and workflow triggering based on incoming communication patterns.", icon: "Mail" },
      { title: "Intelligent Document Processing", description: "Using AI to classify and extract structured data from unstructured contracts, forms, and IDs.", icon: "FileSearch" },
      { title: "OCR & Data Extraction", description: "Enterprise-grade optical character recognition with 99.9% accuracy for scanned analog documents.", icon: "Scan" },
      { title: "Invoice Processing", description: "End-to-end automation of accounts payable, from receipt to approval and ERP synchronization.", icon: "FileText" },
      { title: "Lead Management", description: "Automated scoring and distribution of inbound leads to ensure zero response latency.", icon: "Target" },
      { title: "Employee Onboarding", description: "Streamlining the entire new-hire lifecycle, from document signing to IT asset provisioning.", icon: "UserPlus" },
      { title: "Finance & Accounting", description: "Automating reconciliations, month-end closing, and audit trail generation.", icon: "PieChart" },
      { title: "HR Automation", description: "Optimizing payroll, benefit administration, and performance review workflows.", icon: "Heart" },
      { title: "IT Process Automation", description: "Automated server monitoring, log analysis, and incident response triggering.", icon: "Server" },
      { title: "Chatbot & AI Agents", description: "Deploying autonomous agents that take action across your tools to resolve customer queries instantly.", icon: "MessageSquare" },
      { title: "Workflow Orchestration", description: "Building complex 'If-This-Then-That' logic chains that connect your entire global toolstack.", icon: "Zap" },
      { title: "ERP Integration", description: "Connecting modern digital platforms to legacy SAP, Oracle, or Microsoft Dynamics systems.", icon: "Database" },
      { title: "API Automation", description: "Middleware engineering that connects fragmented tools into a single, high-speed automated ecosystem.", icon: "Link" },
      { title: "Reporting & Dashboards", description: "Automated generation of real-time business intelligence reports without manual export.", icon: "BarChart" },
    ],
    capabilities: [
      { title: "Invoice Automation", description: "Extracting line items and verifying data against purchase orders with zero human touch.", useCase: "Accounts Payable", outcome: "90% Cost Reduction" },
      { title: "Claims Processing", description: "Automatically classifying and validating insurance claims through complex business logic.", useCase: "Insurance Portals", outcome: "95% Faster Settlement" },
      { title: "Payroll Automation", description: "Syncing attendance data with payment processors and tax engines automatically.", useCase: "HR Management", outcome: "Zero Compliance Errors" },
      { title: "Data Entry Automation", description: "Transferring millions of records between legacy software and modern cloud-native apps.", useCase: "Data Migration", outcome: "100x Faster Execution" },
      { title: "Support Automation", description: "Deflecting 60% of common queries using AI agents that can trigger internal API actions.", useCase: "Customer Support", outcome: "Instant Resolutions" },
      { title: "CRM Updates", description: "Auto-updating customer history based on interactions across email, phone, and Slack.", useCase: "Sales Operations", outcome: "Real-time Visibility" },
      { title: "Report Generation", description: "Nightly automated aggregation of sales data into executive PDF reports.", useCase: "Business Intelligence", outcome: "Always-on Insights" },
      { title: "Email Response", description: "Drafting or sending context-aware replies to common customer inquiries using GenAI.", useCase: "Marketing Lead Gen", outcome: "300% Higher CTR" },
      { title: "Recruitment Automation", description: "Auto-screening resumes and scheduling interviews based on calendar availability.", useCase: "Talent Acquisition", outcome: "50% Less Time-to-Hire" },
      { title: "Document Classification", description: "Automatically sorting high volumes of legal documents into the correct digital folders.", useCase: "Legal Tech", outcome: "Absolute Organization" },
    ],
    industries: [
      { name: "Healthcare", useCase: "Medical record synchronization and claims validation." },
      { name: "Finance", useCase: "Automated anti-money laundering (AML) and KYC checks." },
      { name: "Retail", useCase: "Inventory replenishment and multi-channel order sync." },
      { name: "Education", useCase: "Automated student enrollment and course distribution." },
      { name: "Logistics", useCase: "Real-time shipment tracking and automated bill of lading." },
      { name: "Manufacturing", useCase: "Automated quality control reporting and supply chain sync." },
      { name: "Real Estate", useCase: "Automated listing distribution and lead qualification." },
      { name: "HR & Recruitment", useCase: "Automated employee lifecycle management and payroll sync." },
    ],
    process: [
      { title: "Discovery", description: "Auditing manual workflows to identify high-ROI automation targets." },
      { title: "Process Mapping", description: "Deep-dive documentation of 'As-Is' vs 'To-Be' automated flows." },
      { title: "Bot Design", description: "Architecting the logic, exception handling, and credential security." },
      { title: "Development", description: "Building high-reliability RPA scripts and AI-driven API middleware." },
      { title: "Testing", description: "Rigorous UAT in staging to ensure 100% accuracy in data-rich environments." },
      { title: "Deployment", description: "Seamless transition of bots into production with real-time monitoring." },
      { title: "Monitoring", description: "24/7 observability to track bot health and execution logs." },
      { title: "Optimization", description: "Continuous logic refinement to further increase speed and ROI." },
    ],
    techStack: [
      { category: "RPA Platforms", items: ["UiPath", "Automation Anywhere", "Power Automate", "Blue Prism"] },
      { category: "Automation Tools", items: ["Zapier", "Make.com", "n8n", "Selenium"] },
      { category: "AI & OCR", items: ["OpenAI", "AWS Textract", "Google Document AI", "Tesseract"] },
      { category: "Enterprise Stack", items: ["Salesforce", "SAP", "HubSpot", "Microsoft Dynamics"] },
    ],
    benefits: [
      { title: "Reduced Manual Effort", description: "Free your team from repetitive 'grunt work' and drudgery.", icon: "UserCheck" },
      { title: "Improved Accuracy", description: "Achieving 100% data integrity with zero human-induced errors.", icon: "Target" },
      { title: "24/7 Operations", description: "Bots never sleep. Your back-office runs throughout the night.", icon: "Clock" },
      { title: "Absolute Compliance", description: "Every automated action generates an unchangeable audit trail.", icon: "ShieldCheck" },
    ],
    faq: [
      { question: "What is the typical ROI on an RPA project?", answer: "Most enterprises see full ROI within 6 to 12 months, primarily through reduction in human error and thousands of regained man-hours." },
      { question: "Will our service be offline during bot deployment?", answer: "No. Bots interact with your applications just like a human would, meaning no downtime is required for implementation." },
      { question: "What happens if our legacy software UI changes?", answer: "We build our bots with 'Selector-Hardening' and AI computer vision so they can adapt to minor UI shifts without breaking." },
      { question: "Can bots handle unstructured data like PDFs?", answer: "Yes, we integrate Intelligent Document Processing (IDP) that uses AI to extract meaning from non-standard documents." },
      { question: "Is my data secure when using automation bots?", answer: "Absolutely. We implement enterprise-grade encryption and bots can run entirely within your secure VPC environment." },
      { question: "Do you integrate with SAP and Oracle?", answer: "Yes, we specialize in 'Legacy Bridging' for major ERP systems that often lack modern, friendly APIs." },
      { question: "How long does it take to build a single bot?", answer: "Standard workflow bots can often be designed, developed, and deployed in 2 to 4 weeks." },
      { question: "How many hours can RPA save our team?", answer: "Depending on the volume, a single unattended bot can often perform the work of 3 to 5 full-time employees." },
      { question: "What is the difference between Zapier and RPA?", answer: "Zapier uses APIs (behind-the-scenes). RPA uses the actual UI (front-of-house). We often combine both for absolute coverage." },
      { question: "Can automation help with multi-cloud data sync?", answer: "Yes, we build bridges that synchronize data between AWS, Azure, and Google Cloud platforms automatically." },
      { question: "Do we need an internal IT team to maintain the bots?", answer: "No, we offer 'Bot-as-a-Service' packages where we monitor and maintain all automated agents for you." },
      { question: "How do you identify which processes to automate first?", answer: "We look for 'High Volume + High Frequency + Rigid Rules.' If a task is boring and predictable, it should be automated." },
      { question: "Can RPA bots handle complex decision-making?", answer: "Yes, when integrated with AI/ML, bots can handle 'Cognitive Automation' tasks like classifying risk or sentiment." },
      { question: "Is RPA only for large enterprises?", answer: "Not anymore. With tools like Power Automate and Python, mid-market companies can now achieve enterprise-level efficiency." },
      { question: "How do we get started with an automation audit?", answer: "Simply book a consultation. We'll map your manual tasks and provide a clear ROI blueprint before we write any code." },
    ],
    toolLogos: [
      { name: "UiPath", logo: "https://upload.wikimedia.org/wikipedia/commons/b/bf/UiPath_Logo.svg" },
      { name: "Automation Anywhere", logo: "https://upload.wikimedia.org/wikipedia/commons/d/da/Automation_Anywhere_Logo.svg" },
      { name: "Blue Prism", logo: "https://upload.wikimedia.org/wikipedia/commons/a/af/Blue_Prism_logo.svg" },
      { name: "Microsoft Power Automate", logo: "https://upload.wikimedia.org/wikipedia/commons/d/df/Microsoft_Power_Automate.svg" },
      { name: "Salesforce", logo: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Salesforce.com_logo.svg" },
      { name: "Zapier", logo: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Zapier_Logo.svg" },
      { name: "OpenAI", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg" },
      { name: "SAP", logo: "https://upload.wikimedia.org/wikipedia/commons/5/59/SAP_2011_logo.svg" },
      { name: "n8n", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/N8n-logo.svg" },
      { name: "Make.com", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Make.com_Logo.svg" },
      { name: "Selenium", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Selenium_Logo.png" },
      { name: "Python", logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" },
      { name: "Node.js", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg" },
    ],
    caseStudy: {
      projectSlug: "supply-chain-modernization",
      overview: "Automated 85,000 monthly transactions for a logistics leader, reducing processing cost by 70% and increasing accuracy to 100%.",
    },
    finalCTA: {
      headline: "Stop Boring Your Brilliant Team.",
      description: "Let's engineer an autonomous digital workforce that puts your growth back in the fast lane.",
      buttonLabel: "Book an Automation Audit",
    },
  },
  "cloud-infrastructure": {
    title: "Cloud & Infrastructure",
    slug: "cloud-infrastructure",
    shortDescription: "Cloud-native architecture, DevOps, deployment pipelines, serverless systems, APIs, monitoring, and scalable infrastructure.",
    description: "We design and manage the resilient infrastructure that powers modern software, ensuring maximum uptime and linear scalability.",
    icon: "Cloud",
    technologies: ["Terraform", "Kubernetes", "Azure", "GCP"],
    features: ["AWS/Azure/GCP", "DevOps & CI/CD", "Serverless Computing", "Security & Compliance"],
    hero: {
      badge: "DevOps & Cloud",
      headline: "Cloud & Infrastructure",
      subheadline: "Unbreakable foundations. Infinite scale.",
      intro: "We engineer high-performance, resilient cloud environments that serve as the backbone for modern software. From automated CI/CD pipelines to global Kubernetes clusters, we build for maximum uptime.",
      primaryCTA: { label: "Scale Your Infrastructure", href: "/contact" },
      secondaryCTA: { label: "Explore DevOps", href: "#solutions" },
      stats: [
        { label: "Uptime Focus", value: "99.99%" },
        { label: "Deployment Speed", value: "Instant" },
        { label: "Security First", value: "Hardened" },
      ],
    },
    about: {
      description: "Modern infrastructure is code. We leverage Infrastructure as Code (IaC) to build reproducible, secure, and infinitely scalable environments on AWS, GCP, and Azure.",
      whyNeeded: "As your user base grows, manual server management becomes a bottleneck. A modern cloud-native stack allows you to scale up or down automatically, saving costs and ensuring stability.",
      problemsSolved: [
        "Slow, manual deployment processes that cause downtime",
        "High cloud costs due to unoptimized resource allocation",
        "Security vulnerabilities in unpatched legacy servers",
        "Inconsistent environments causing 'it works on my machine' bugs",
      ],
    },
    solutions: [
      { title: "Cloud-Native Strategy", description: "Architecting serverless and containerized systems for modern web and mobile platforms.", icon: "Cpu" },
      { title: "DevOps & CI/CD", description: "Building automated pipelines (GitHub Actions, Jenkins) that ship code to production safely in seconds.", icon: "RefreshCw" },
      { title: "Infrastructure as Code", description: "Managing your entire cloud environment through version-controlled Terraform or Pulumi scripts.", icon: "FileCode" },
      { title: "Kubernets Orchestration", description: "Global container management for high-availability enterprise-grade applications.", icon: "Cloud" },
      { title: "Security Hardening", description: "Implementing VPCs, WAFs, and automated security scans across your entire stack.", icon: "Shield" },
    ],
    capabilities: [
      { title: "Auto-Scaling Architectures", description: "Systems that detect traffic spikes and automatically spin up resources to handle the load.", useCase: "E-commerce Peak Sales", outcome: "Zero Downtime" },
      { title: "Multi-Cloud Strategy", description: "Avoid vendor lock-in with architectures that can run across AWS, Azure, and private clouds.", useCase: "Enterprise Continuity", outcome: "High Resiliency" },
      { title: "Monitoring & Observability", description: "Setting up real-time dashboards (Prometheus, Grafana) to catch bugs before users do.", useCase: "Mission-Critical SaaS", outcome: "Instant Bug Detection" },
    ],
    industries: ["SaaS", "Fintech", "HealthTech", "Media", "Public Sector"],
    process: [
      { title: "Infra Audit", description: "Assessing current cloud spend, security, and bottlenecks." },
      { title: "Architecture Design", description: "Crafting a scalable blueprint for your unique application needs." },
      { title: "Environment Setup", description: "Writing IaC scripts to provision staging and production environments." },
      { title: "Pipeline Building", description: "Implementing automated CI/CD workflows for seamless code shipping." },
      { title: "Security Audit", description: "Penetration testing and hardening all server endpoints." },
      { title: "24/7 Monitoring", description: "Ongoing observability and zero-downtime maintenance." },
    ],
    techStack: [
      { category: "Cloud Providers", items: ["AWS", "Azure", "GCP", "DigitalOcean", "Vultr", "Linode"] },
      { category: "Orchestration", items: ["Kubernetes", "Docker Swarm", "Nomad", "Helm", "Istio"] },
      { category: "IaC & Ops", items: ["Terraform", "Pulumi", "Ansible", "Chef", "Puppet", "CloudFormation"] },
      { category: "CI/CD & Monitoring", items: ["GitHub Actions", "GitLab CI", "Jenkins", "Prometheus", "Grafana", "Datadog"] },
    ],
    toolLogos: [
      { name: "AWS", logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg" },
      { name: "Azure", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Microsoft_Azure_Logo.svg" },
      { name: "GCP", logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/Google_Cloud_logo.svg" },
      { name: "Kubernetes", logo: "https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_v2.svg" },
      { name: "Docker", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Docker_%28container_engine%29_logo.svg" },
      { name: "Terraform", logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/Terraform_Logo.svg" },
      { name: "GitHub", logo: "https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg" },
      { name: "GitLab", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e1/GitLab_logo.svg" },
      { name: "Prometheus", logo: "https://upload.wikimedia.org/wikipedia/commons/3/38/Prometheus_software_logo.svg" },
      { name: "Grafana", logo: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Grafana_logo.svg" },
      { name: "Datadog", logo: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Datadog_logo.svg" },
    ],
    benefits: [
      { title: "Infinite Scale", description: "Infrastructure that grows with your business without intervention.", icon: "ArrowUpRight" },
      { title: "Bulletproof Security", description: "Automated patches and hardened networking for absolute peace of mind.", icon: "ShieldCheck" },
      { title: "Cost Optimization", description: "Only pay for exactly what you use through serverless and spot instances.", icon: "TrendingDown" },
      { title: "Lightning Fast Ship", description: "Move from code to production in minutes, not days.", icon: "Zap" },
    ],
    faq: [
      { question: "How do you help us reduce our monthly cloud bill?", answer: "We use cost-allocation tags and resource optimization (right-sizing) to ensure you aren't paying for 'idle' server time. Our typical clients save 20-40%." },
      { question: "What is Infrastructure as Code (IaC)?", answer: "It means we write scripts to manage your servers. This makes your environment reproducible, version-controlled, and easy to recover in case of disasters." },
      { question: "Can you help us migrate from on-premise to the cloud?", answer: "Absolutely. We specialize in 'Lift and Shift' or 'Refactor' strategies to bring your local servers into the modern cloud era safely." },
    ],
    caseStudy: {
      projectSlug: "saas-scaling-infrastructure",
      overview: "Optimized a SaaS provider's Kubernetes cluster, reducing their AWS spend by 35% while improving load speeds by 2x.",
    },
    finalCTA: {
      headline: "Build on bedrock.",
      description: "Let's engineer a cloud infrastructure that is as ambitious as your business goals.",
      buttonLabel: "Optimize Your Cloud",
    },
  },
  "data-analytics": {
    title: "Data & Analytics",
    slug: "data-analytics",
    shortDescription: "Data engineering, BI dashboards, predictive analytics, reporting systems, and real-time business intelligence platforms.",
    description: "Turn raw data into decision-making power. We build custom data pipelines and real-time visualization dashboards for enterprise-wide intelligence.",
    icon: "BarChart3",
    technologies: ["Snowflake", "dbt", "Power BI", "Tableau"],
    features: ["Data Pipelines", "Real-time Dashboards", "Big Data Engineering", "Business Intelligence"],
    hero: {
      badge: "Data Intelligence",
      headline: "Data & Analytics",
      subheadline: "Raw data. Actionable intelligence.",
      intro: "We engineer the data pipelines and interactive dashboards that turn fragmented information into your most powerful strategic asset. From real-time streams to predictive modeling, we build for clarity.",
      primaryCTA: { label: "Architect Your Data", href: "/contact" },
      secondaryCTA: { label: "Explore BI Tools", href: "#solutions" },
      stats: [
        { label: "Data Processed", value: "10TB+" },
        { label: "Insight Latency", value: "<1s" },
        { label: "Decisions Powered", value: "Millions" },
      ],
    },
    about: {
      description: "In the modern enterprise, data is the fuel. We build the engine. We specialize in transforming messy, siloed data into structured, real-time insights that can be understood from the boardroom to the field.",
      whyNeeded: "Static reports are a thing of the past. To stay competitive, you need 'Decision-Grade' data—real-time, accurate, and visually intuitive information that tells you what happened and what will happen next.",
      problemsSolved: [
        "Eliminates hours spent on manual spreadsheet reporting",
        "Breaks down silos between departments (Sales, Ops, Finance)",
        "Reduces 'Insight Latency'—get answers in seconds, not days",
        "Predicts customer behavior and inventory needs with ML",
      ],
    },
    solutions: [
      { title: "Enterprise Data Warehousing", description: "Centralizing all your business data into high-performance warehouses like Snowflake or BigQuery.", icon: "Database" },
      { title: "Real-Time BI Dashboards", description: "Interactive, pixel-perfect visualizations that provide a live pulse of your entire organization.", icon: "BarChart3" },
      { title: "Data Pipeline Engineering (ETL)", description: "Automated pipelines that ingest, cleanse, and transform data from 100+ sources instantly.", icon: "Share2" },
      { title: "Predictive Analytics", description: "Using machine learning to forecast sales, detect anomalies, and optimize supply chains.", icon: "TrendingUp" },
      { title: "Data Governance & Security", description: "Ensuring your data is compliant (GDPR/SOC2) and restricted to the right users.", icon: "Lock" },
    ],
    capabilities: [
      { title: "Streaming Data Architectures", description: "Processing millions of events per second for instant notification and real-time reaction.", useCase: "Fintech Fraud Detection", outcome: "Real-time Prevention" },
      { title: "Self-Service BI", description: "Empowering your non-technical staff to build their own reports through intuitive drag-and-drop tools.", useCase: "Marketing Attribution", outcome: "Independent Teams" },
      { title: "Big Data Modeling", description: "Structuring massive datasets for high-speed querying and advanced data science research.", useCase: "Supply Chain Forecasting", outcome: "95% Forecast Accuracy" },
    ],
    industries: ["Finance", "Retail", "SaaS", "GovTech", "HealthTech"],
    process: [
      { title: "Data Discovery", description: "Identifying all data sources and documenting business KPIs." },
      { title: "Pipeline Design", description: "Architecting the ETL/ELT flows and data warehouse schema." },
      { title: "Engineering", description: "Building automated ingestion scripts and data transformation layers." },
      { title: "Dashboarding", description: "Designing the visual interface for high-level and granular insights." },
      { title: "Validation", description: "Rigorous data reconciliation to ensure 100% reporting accuracy." },
      { title: "Scale Up", description: "Continuous performance tuning for growing data volumes." },
    ],
    techStack: [
      { category: "Warehouses", items: ["Snowflake", "BigQuery", "Redshift", "Databricks", "ClickHouse", "TiDB"] },
      { category: "Ingestion/ETL", items: ["dbt", "Fivetran", "Airflow", "Python", "Prefect", "Dagster"] },
      { category: "Visualization", items: ["Power BI", "Tableau", "Looker", "D3.js", "Metabase", "Superset"] },
      { category: "Processing", items: ["Spark", "Kafka", "Pandas", "Flink", "Ray"] },
    ],
    toolLogos: [
      { name: "Snowflake", logo: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Snowflake_Logo.svg" },
      { name: "BigQuery", logo: "https://upload.wikimedia.org/wikipedia/commons/0/0a/BigQuery_logo.svg" },
      { name: "Tableau", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Tableau_Logo.png" },
      { name: "PowerBI", logo: "https://upload.wikimedia.org/wikipedia/commons/c/cf/New_Power_BI_Logo.svg" },
      { name: "Airflow", logo: "https://upload.wikimedia.org/wikipedia/commons/d/de/AirflowLogo.png" },
      { name: "dbt", logo: "https://upload.wikimedia.org/wikipedia/commons/d/da/Dbt_logo.svg" },
      { name: "Python", logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg" },
      { name: "Spark", logo: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Apache_Spark_logo.svg" },
      { name: "Kafka", logo: "https://upload.wikimedia.org/wikipedia/commons/5/53/Apache_kafka_wordmark.svg" },
    ],
    benefits: [
      { title: "Strategic Clarity", description: "Know exactly which levers to pull to drive growth.", icon: "Eye" },
      { title: "Operational Speed", description: "Instant access to metrics eliminates boardroom guesswork.", icon: "Zap" },
      { title: "Cost Savings", description: "Identify and eliminate waste across your entire operation.", icon: "DollerSign" },
      { title: "Future Proof", description: "Infrastructure that can handle tomorrow's massive data growth.", icon: "ArrowUpRight" },
    ],
    faq: [
      { question: "Can you connect to our old legacy databases?", answer: "Yes. We specialize in building secure data bridges that can pull information from legacy SQL servers, ERPs, and even flat files into a modern warehouse." },
      { question: "Is our data secure during processing?", answer: "Absolutely. We implement end-to-end encryption and SOC2-compliant data practices, ensuring your sensitive business info never leaves a secure environment." },
      { question: "How long does it take to see the first dashboard?", answer: "We follow an agile 'Value-First' approach. Typically, we can have your most critical KPI dashboard live in 3-4 weeks." },
    ],
    caseStudy: {
      projectSlug: "e-commerce-analytics-engine",
      overview: "Built a real-time attribution engine that helped a major retailer optimize their $2M monthly ad spend, increasing ROAS by 40%.",
    },
    finalCTA: {
      headline: "See what others miss.",
      description: "Let's engineer a data strategy that provides absolute clarity in an uncertain market.",
      buttonLabel: "Start Your Data Audit",
    },
  },
  "modernization-migration": {
    title: "Modernization & Migration",
    slug: "modernization-migration",
    shortDescription: "Legacy software transformation, desktop-to-web migration, cloud migration, database upgrades, and platform modernization.",
    description: "Stop being held back by outdated tech. We specialize in safely and rapidly refactoring legacy code into modern, maintainable platforms.",
    icon: "Shuffle",
    technologies: ["Express", "MongoDB", "Redux", "GraphQL"],
    features: ["Legacy Refactoring", "Database Migration", "Version Upgrades", "API Modernization"],
    hero: {
      badge: "Legacy Refactoring",
      headline: "Modernization & Migration",
      subheadline: "Shed the technical debt. Accelerate growth.",
      intro: "We specialize in the high-stakes engineering of migrating mission-critical legacy systems to modern, cloud-native architectures. No downtime, no data loss—just a clean path to the future.",
      primaryCTA: { label: "Modernize Your Stack", href: "/contact" },
      secondaryCTA: { label: "View Migration Path", href: "#solutions" },
      stats: [
        { label: "Systems Migrated", value: "50+" },
        { label: "Technical Debt Cut", value: "80%" },
        { label: "Downtime", value: "Zero" },
      ],
    },
    about: {
      description: "Legacy software is the largest hidden cost in enterprise business. We don't just 'patch' old code; we systematically refactor, containerize, and modernize your assets to meet modern standards of speed and security.",
      whyNeeded: "Holding onto 10-year-old stacks limits your ability to hire talent, integrate with new APIs, and scale your user base. Migration isn't an expense; it's an investment in your company's longevity.",
      problemsSolved: [
        "Eliminates the risk of sudden system failure on unmaintained tech",
        "Reduces insane maintenance costs of 'zombie' servers",
        "Enables faster feature releases by removing code spaghetti",
        "Secures your data against modern vulnerabilities found in old versions",
      ],
    },
    solutions: [
      { title: "Monolith-to-Microservices", description: "Decomposing complex, slow monolithic code into modular, independently scalable services.", icon: "Layers" },
      { title: "Desktop-to-Web Migration", description: "Transforming legacy desktop applications into high-performance, cross-platform web experiences.", icon: "Monitor" },
      { title: "Database Modernization", description: "Migrating old SQL Server or Oracle instances to modern, cloud-native distributed databases.", icon: "Database" },
      { title: "Cloud Re-platforming", description: "Moving from on-premise hardware to fully managed, auto-scaling cloud environments.", icon: "Cloud" },
      { title: "Version & Language Upgrades", description: "Safe, systematic upgrading of core languages (Java, Python, .NET) and framework versions.", icon: "ArrowUpCircle" },
    ],
    capabilities: [
      { title: "Code Refactoring", description: "Cleaning up legacy debt while maintaining 100% of the original business logic and security.", useCase: "Enterprise ERP Updates", outcome: "60% Faster CI/CD" },
      { title: "Data Reconciliation", description: "Ensuring 100% data integrity during migration with automated verification scripts.", useCase: "Fintech Migrations", outcome: "Zero Data Loss" },
      { title: "Integration Bridges", description: "Building temporary API adapters so new systems can communicate with old modules during the shift.", useCase: "Phased Modernization", outcome: "Operational Continuity" },
    ],
    industries: ["Finance", "Insurance", "Logistics", "Public Sector", "Manufacturing"],
    process: [
      { title: "Debt Audit", description: "Assessing the current stack and identifying the highest-risk modules." },
      { title: "Blueprint", description: "Mapping out the new architecture and phased migration steps." },
      { title: "Prototyping", description: "Migrating a single non-critical module as a proof of concept." },
      { title: "Engineering", description: "Systematic refactoring and data migration in controlled sprints." },
      { title: "Shadow Run", description: "Running the new system in parallel with the old to verify results." },
      { title: "Cutover", description: "Final switch to the modernized stack with zero impact on users." },
    ],
    techStack: [
      { category: "Modern Target", items: ["Next.js", "Node.js", "Go", "Kubernetes", "Django", "FastAPI"] },
      { category: "Migration Tools", items: ["Docker", "Terraform", "AWS DMS", "Kafka", "Redis", "Debezium"] },
      { category: "Legacy Exp.", items: ["ASP.NET", "Java EE", "PHP", "COBOL Modernization", "Mainframe Ops"] },
      { category: "Databases", items: ["PostgreSQL", "MongoDB", "Snowflake", "Oracle to Postgres"] },
    ],
    toolLogos: [
      { name: "AWS", logo: "https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg" },
      { name: "Docker", logo: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Docker_%28container_engine%29_logo.svg" },
      { name: "Kubernetes", logo: "https://upload.wikimedia.org/wikipedia/commons/3/39/Kubernetes_logo_v2.svg" },
      { name: "PostgreSQL", logo: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg" },
      { name: "Node.js", logo: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg" },
      { name: "Go", logo: "https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg" },
    ],
    benefits: [
      { title: "Massive Agility", description: "Release features in days, not months, on a modern codebase.", icon: "Zap" },
      { title: "Talent Attraction", description: "Top engineers want to work on modern stacks, not legacy debt.", icon: "Users" },
      { title: "Cost Collapse", description: "Reduce maintenance and server costs by up to 50%.", icon: "TrendingDown" },
      { title: "Unbreakable Security", description: "Modern stacks are built with today's threats in mind.", icon: "ShieldCheck" },
    ],
    faq: [
      { question: "Will our users notice the migration?", answer: "Ideally, they will notice the system becoming much faster and more reliable. We handle the technical 'plumbing' behind the scenes so there is zero interruption." },
      { question: "Is it better to rebuild from scratch or refactor?", answer: "It depends. Refactoring is lower risk, while rebuilding offers more freedom. We'll perform a 'Repair vs Replace' audit to help you decide." },
      { question: "How do you ensure our data isn't lost?", answer: "We use automated data reconciliation and check-summing tools that verify every single record after it moves to the new system." },
    ],
    caseStudy: {
      projectSlug: "fintech-core-modernization",
      overview: "Migrated a legacy banking backend to a modern microservices architecture, reducing transaction processing time by 70%.",
    },
    finalCTA: {
      headline: "Stop paying for the past.",
      description: "Let's engineer a modernization roadmap that prepares your business for the next decade of growth.",
      buttonLabel: "Get a Technical Audit",
    },
  },
};




