import { Service } from "@/types";

export const SERVICES: Service[] = [
  {
    title: "AI & Intelligent Systems",
    slug: "ai-intelligent-systems",
    shortDescription: "Advanced AI, machine learning, generative AI, computer vision, NLP, and intelligent agent systems built for modern businesses.",
    description: "Push the boundaries of what's possible with custom AI agents, large language models (LLMs), and predictive analytics systems that learn and adapt to your business data.",
    icon: "Brain",
    technologies: ["OpenAI", "PyTorch", "TensorFlow", "LangChain"],
    features: ["Generative AI", "Custom AI Agents", "Predictive Analytics", "NLP & Computer Vision"],
  },
  {
    title: "Intelligent Automation (RPA+AI)",
    slug: "intelligent-automation",
    shortDescription: "Enterprise-grade RPA, intelligent workflows, CRM automation, document processing, and AI-powered operations for global scale.",
    description: "We eliminate operational friction by replacing repetitive manual tasks with high-reliability autonomous agents and intelligent software workflows.",
    icon: "Zap",
    technologies: ["UiPath", "Power Automate", "Python", "Zapier", "OpenAI"],
    features: ["Robotic Process Automation", "Intelligent Workflows", "AI Document Processing", "CRM & ERP Automation"],
  },
  {
    title: "Product & Enterprise Engineering",
    slug: "product-enterprise-engineering",
    shortDescription: "Custom SaaS platforms, ERP, CRM, HRMS, and scalable business applications designed for complex global operations.",
    description: "From idea to market-ready SaaS or enterprise-wide internal systems, we engineer scalable, high-performance software using modern architecture and robust security.",
    icon: "Code2",
    technologies: ["React", "Node.js", "TypeScript", "PostgreSQL", "Java", "C#"],
    features: ["SaaS & MVP Dev", "Custom ERP & CRM", "HRMS & Internal Portals", "Scalable App Architecture"],
  },
  {
    title: "Digital Transformation",
    slug: "digital-transformation",
    shortDescription: "End-to-end modernization, process optimization, technology consulting, and digital architecture for future-ready organizations.",
    description: "We help institutions and enterprises migrate from legacy systems to high-performance, cloud-native technology stacks. Our approach covers strategic consulting, architecture planning, and seamless zero-downtime execution.",
    icon: "RefreshCw",
    technologies: ["Next.js", "Python", "AWS", "Docker"],
    features: ["Legacy Modernization", "Cloud Migration", "Strategy & Consulting", "Infrastructure Audit"],
  },
  {
    title: "Website & Experience Design",
    slug: "website-design",
    shortDescription: "Premium websites, 3D experiences, landing pages, e-commerce platforms, and high-performance digital interfaces.",
    description: "We craft visually stunning, high-performance websites and digital experiences that blend aesthetic excellence with technical precision.",
    icon: "Monitor",
    technologies: ["Next.js", "Three.js", "Tailwind CSS", "Framer Motion"],
    features: ["Premium Marketing Sites", "3D Web Experiences", "E-commerce Platforms", "UI/UX Design"],
  },
  {
    title: "Mobile App Engineering",
    slug: "mobile-engineering",
    shortDescription: "Cross-platform Android and iOS applications for startups, enterprises, internal teams, and customer-facing products.",
    description: "We develop high-performance, cross-platform mobile applications that prioritize user experience and technical efficiency.",
    icon: "Smartphone",
    technologies: ["React Native", "Flutter", "Swift", "Kotlin"],
    features: ["iOS & Android Apps", "React Native", "UI/UX Motion", "Mobile Backend Integration"],
  },
  {
    title: "Cloud & Infrastructure",
    slug: "cloud-infrastructure",
    shortDescription: "Cloud-native architecture, DevOps, deployment pipelines, serverless systems, APIs, monitoring, and scalable infrastructure.",
    description: "We design and manage the resilient infrastructure that powers modern software, ensuring maximum uptime and linear scalability.",
    icon: "Cloud",
    technologies: ["Terraform", "Kubernetes", "Azure", "GCP"],
    features: ["AWS/Azure/GCP", "DevOps & CI/CD", "Serverless Computing", "Security & Compliance"],
  },
  {
    title: "Data & Analytics",
    slug: "data-analytics",
    shortDescription: "Data engineering, BI dashboards, predictive analytics, reporting systems, and real-time business intelligence platforms.",
    description: "Turn raw data into decision-making power. We build custom data pipelines and real-time visualization dashboards for enterprise-wide intelligence.",
    icon: "BarChart3",
    technologies: ["Snowflake", "dbt", "Power BI", "Tableau"],
    features: ["Data Pipelines", "Real-time Dashboards", "Big Data Engineering", "Business Intelligence"],
  },
  {
    title: "Modernization & Migration",
    slug: "modernization-migration",
    shortDescription: "Legacy software transformation, desktop-to-web migration, cloud migration, database upgrades, and platform modernization.",
    description: "Stop being held back by outdated tech. We specialize in safely and rapidly refactoring legacy code into modern, maintainable platforms.",
    icon: "Shuffle",
    technologies: ["Express", "MongoDB", "Redux", "GraphQL"],
    features: ["Legacy Refactoring", "Database Migration", "Version Upgrades", "API Modernization"],
  },
];
